// Trail IDs shown in the landing-page "Featured" grid. Hand-picked for
// visual variety, regional spread, and name recognition.
//
// Order matters — this is the on-screen layout left-to-right, top-to-bottom.
// Coordinate data for these trails lives in `lib/featured-coords.json`,
// regenerated by `scripts/extract-featured-coords.mjs` when the list changes.
export const FEATURED_IDS = [
  "half-dome",
  "skyline-paradise",
  "hurricane-hill",
  "garfield-peak",
  "fern-canyon",
  "ryan-mountain",
];
