import type { Trail, Popularity, Scenery } from "./types";

// Popularity tier per trail id. Read as a positive descriptor of the
// experience; "Backcountry" is not a danger label, it's a feature for
// people who want solitude (with the corresponding self-reliance).
//
// Calibration: based on AllTrails review counts, social-media presence,
// and traffic-per-mile estimates. Famous-but-linear thru-hikes (PCT,
// JMT) sit in `backcountry` because per-day-of-effort you'll see far
// fewer people than on a 4 mi viewpoint hike.
const POPULARITY_BY_ID: Record<string, Popularity> = {
  // Iconic — instantly recognized; you'll have company at viewpoints
  "half-dome": "iconic",
  "mist-trail": "iconic",
  "multnomah-wahkeena": "iconic",
  "hurricane-hill": "iconic",
  "hall-of-mosses": "iconic",
  "smith-rock": "iconic",
  "fern-canyon": "iconic",
  "bumpass-hell": "iconic",
  "mt-si": "iconic",
  "garfield-peak": "iconic",
  "maple-pass": "iconic",
  ewoldsen: "iconic",
  "sol-duc-falls": "iconic",
  "eagle-creek": "iconic",
  "skyline-paradise": "iconic",

  // Popular — every active hiker knows these; reliable foot traffic
  "clouds-rest": "popular",
  "upper-yosemite-falls": "popular",
  "cathedral-lakes": "popular",
  "sentinel-taft": "popular",
  "mt-whitney": "popular",
  "cascade-pass": "popular",
  "blue-lake": "popular",
  "naches-peak": "popular",
  burroughs: "popular",
  "storm-king": "popular",
  "mt-tam": "popular",
  "mt-diablo": "popular",
  "mt-baldy": "popular",
  "san-jacinto": "popular",
  "ryan-mountain": "popular",
  alamere: "popular",
  "tomales-point": "popular",
  "south-sister": "popular",
  "lassen-peak": "popular",
  "high-peaks-pinnacles": "popular",
  "andrew-molera": "popular",
  smugglers: "popular",

  // Steady — established and well-documented but with more breathing room
  "hidden-lake": "steady",
  heliotrope: "steady",
  "shi-shi": "steady",
  "high-divide": "steady",
  "tolmie-peak": "steady",
  wonderland: "steady",
  timberline: "steady",
  jmt: "steady",

  // Backcountry — multi-day or genuinely remote; expect long stretches alone
  "rae-lakes": "backcountry",
  "tahoe-rim": "backcountry",
  "lost-coast": "backcountry",
  "telescope-peak": "backcountry",
  pct: "backcountry",

  // ----- New batch: filling West-Coast gap regions -----
  "mist-falls": "popular",
  "lakes-trail": "steady",
  "moro-rock": "iconic",
  "tokopah-falls": "popular",
  "tom-dick-harry": "popular",
  "mcneil-point": "steady",
  "tamanawas-falls": "popular",
  "cooper-spur": "steady",
  "cinder-cone": "steady",
  "hidden-valley": "iconic",
  "lost-palms-oasis": "steady",
  "forty-nine-palms": "popular",
  "kendall-katwalk": "popular",
  "cutthroat-pass": "popular",
  "marymere-falls": "popular",
  "lake-22": "iconic",
  "chain-lakes": "popular",
  "eaton-canyon": "iconic",
  "solstice-canyon": "popular",
  "mt-st-helens": "popular",
  "mission-peak": "iconic",
  "point-lobos": "iconic",
  "pfeiffer-falls": "popular",
  "mt-scott-crater": "steady",
  "angels-rest": "iconic",
};

/** Scenery rating, 1–5. See lib/types.ts.  Calibration:
 *  5 = legendary (Half Dome, Crater Lake rim, Hurricane Hill);
 *  4 = spectacular (most National-Park alpine);
 *  3 = very scenic (Bay Area summit views, urban-edge canyons);
 *  2 = pleasant (training mountains, forest connectors). */
const SCENERY_BY_ID: Record<string, Scenery> = {
  // Yosemite + High Sierra
  "half-dome": 5,
  "clouds-rest": 5,
  "mist-trail": 5,
  "upper-yosemite-falls": 4,
  "cathedral-lakes": 5,
  "sentinel-taft": 5,
  "mt-whitney": 5,
  jmt: 5,
  "rae-lakes": 5,
  "tahoe-rim": 5,
  // Cascades / Rainier / N. Cascades
  "skyline-paradise": 5,
  burroughs: 4,
  "tolmie-peak": 4,
  wonderland: 5,
  "naches-peak": 4,
  "cascade-pass": 5,
  "blue-lake": 4,
  "maple-pass": 5,
  "hidden-lake": 5,
  heliotrope: 4,
  "mt-si": 2,
  // Olympic
  "hurricane-hill": 5,
  "hall-of-mosses": 5,
  "shi-shi": 5,
  "high-divide": 5,
  "sol-duc-falls": 4,
  "storm-king": 4,
  // Oregon
  "multnomah-wahkeena": 5,
  "eagle-creek": 4,
  "smith-rock": 5,
  "south-sister": 5,
  "garfield-peak": 5,
  timberline: 5,
  // NorCal
  "fern-canyon": 4,
  "lassen-peak": 4,
  "bumpass-hell": 4,
  "lost-coast": 5,
  "telescope-peak": 4,
  // SoCal / desert
  "mt-tam": 3,
  "mt-diablo": 3,
  "mt-baldy": 4,
  "san-jacinto": 4,
  "ryan-mountain": 4,
  // Big Sur / Bay
  alamere: 4,
  "tomales-point": 4,
  ewoldsen: 4,
  "andrew-molera": 4,
  smugglers: 4,
  "high-peaks-pinnacles": 4,
  // Thru-hike
  pct: 5,

  // ----- New batch -----
  "mist-falls": 4,
  "lakes-trail": 4,
  "moro-rock": 4,
  "tokopah-falls": 3,
  "tom-dick-harry": 4,
  "mcneil-point": 5,
  "tamanawas-falls": 3,
  "cooper-spur": 5,
  "cinder-cone": 4,
  "hidden-valley": 4,
  "lost-palms-oasis": 4,
  "forty-nine-palms": 4,
  "kendall-katwalk": 5,
  "cutthroat-pass": 5,
  "marymere-falls": 3,
  "lake-22": 4,
  "chain-lakes": 5,
  "eaton-canyon": 2,
  "solstice-canyon": 3,
  "mt-st-helens": 5,
  "mission-peak": 2,
  "point-lobos": 5,
  "pfeiffer-falls": 3,
  "mt-scott-crater": 5,
  "angels-rest": 4,
};

/** Endpoint coordinates for the few genuinely point-to-point trails. Loops
 *  and out-and-backs return to `trailhead` and stay unset. */
const ENDPOINT_BY_ID: Record<string, { lat: number; lng: number; name: string }> = {
  jmt: { lat: 36.5785, lng: -118.2923, name: "Mt Whitney summit" },
  pct: { lat: 49.0008, lng: -120.7717, name: "Manning Park, BC (Northern Terminus)" },
  "lost-coast": { lat: 40.0223, lng: -124.0717, name: "Black Sands Beach" },
};

const RAW_TRAILS: Omit<Trail, "popularity" | "scenery">[] = [
  // ========== Yosemite + High Sierra ==========
  {
    id: "half-dome",
    name: "Half Dome via Mist Trail",
    region: "yosemite-sierra",
    state: "CA",
    parkUnit: "Yosemite National Park",
    difficulty: "extreme",
    type: "day",
    ecosystem: "alpine",
    lengthMiles: 14.2,
    elevationGainFt: 4800,
    trailhead: { lat: 37.733, lng: -119.5575 },
    permitRequired: true,
    bestSeasons: ["summer", "fall"],
    description:
      "The most iconic day hike in the Sierra: thunderous waterfalls, granite staircases, and the legendary cable route up the back of Half Dome's 8,800-ft face. A 14-hour day for most. Cables typically up late May through mid-October.",
    highlights: ["Vernal & Nevada Falls", "Sub Dome cables", "Yosemite Valley summit views"],
    externalUrl: "https://www.nps.gov/yose/planyourvisit/halfdome.htm",
  },
  {
    id: "clouds-rest",
    name: "Cloud's Rest",
    region: "yosemite-sierra",
    state: "CA",
    parkUnit: "Yosemite National Park",
    difficulty: "hard",
    type: "day",
    ecosystem: "alpine",
    lengthMiles: 12,
    elevationGainFt: 2300,
    trailhead: { lat: 37.8307, lng: -119.4663 },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "A skinny granite spine rising 4,500 ft above Yosemite Valley, with what many consider the best view in the park — including a profile of Half Dome from above.",
    highlights: ["Granite ridge walk", "360° Sierra panorama", "View down on Half Dome"],
  },
  {
    id: "mist-trail",
    name: "Mist Trail (Vernal & Nevada Falls)",
    region: "yosemite-sierra",
    state: "CA",
    parkUnit: "Yosemite National Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "alpine",
    lengthMiles: 5.4,
    elevationGainFt: 1900,
    trailhead: { lat: 37.733, lng: -119.5575 },
    permitRequired: false,
    bestSeasons: ["spring", "summer"],
    description:
      "Yosemite Valley's signature waterfall trail. Climbs granite stairs straight through the spray of 317-ft Vernal Fall before continuing to the brink of 594-ft Nevada Fall.",
    highlights: ["Walk through waterfall mist", "Emerald Pool", "Liberty Cap"],
  },
  {
    id: "upper-yosemite-falls",
    name: "Upper Yosemite Falls",
    region: "yosemite-sierra",
    state: "CA",
    parkUnit: "Yosemite National Park",
    difficulty: "hard",
    type: "day",
    ecosystem: "alpine",
    lengthMiles: 7.2,
    elevationGainFt: 2700,
    trailhead: { lat: 37.7501, lng: -119.5972 },
    permitRequired: false,
    bestSeasons: ["spring", "summer", "fall"],
    description:
      "Switchbacks ascend the cliff next to North America's tallest waterfall. The brink view is exhilarating — and the falls themselves slow to a trickle by August.",
    highlights: ["Columbia Rock viewpoint", "Top of 2,425-ft falls", "Yosemite Point side trip"],
  },
  {
    id: "cathedral-lakes",
    name: "Cathedral Lakes",
    region: "yosemite-sierra",
    state: "CA",
    parkUnit: "Yosemite National Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "subalpine",
    lengthMiles: 7,
    elevationGainFt: 1000,
    trailhead: { lat: 37.873, lng: -119.3829 },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "Tuolumne Meadows' most beloved hike — a gentle climb through lodgepole forest to a pair of glacier-carved lakes beneath the spires of Cathedral Peak.",
    highlights: ["Cathedral Peak reflection", "Wildflower meadows", "Tioga Pass scenery"],
  },
  {
    id: "sentinel-taft",
    name: "Sentinel Dome + Taft Point Loop",
    region: "yosemite-sierra",
    state: "CA",
    parkUnit: "Yosemite National Park",
    difficulty: "easy",
    type: "day",
    ecosystem: "subalpine",
    lengthMiles: 5,
    elevationGainFt: 800,
    trailhead: { lat: 37.7128, lng: -119.5867 },
    permitRequired: false,
    bestSeasons: ["spring", "summer", "fall"],
    description:
      "Two of Yosemite's best viewpoints in a single short loop. Sentinel Dome offers a 360° panorama; Taft Point puts you on a 3,000-ft cliff edge with no railings.",
    highlights: ["Cliff-edge fissures at Taft Point", "Sentinel Dome 360 view", "Sunset spot"],
  },
  {
    id: "mt-whitney",
    name: "Mt Whitney Trail",
    region: "yosemite-sierra",
    state: "CA",
    parkUnit: "Inyo National Forest",
    difficulty: "extreme",
    type: "day",
    ecosystem: "alpine",
    lengthMiles: 22,
    elevationGainFt: 6600,
    trailhead: { lat: 36.5874, lng: -118.2398 },
    permitRequired: true,
    bestSeasons: ["summer"],
    description:
      "The contiguous USA's highest summit at 14,505 ft. A relentless 22-mile out-and-back gaining over 6,000 ft, with 99 switchbacks and altitude that breaks most hikers. Lottery permit required.",
    highlights: ["Highest peak in lower 48", "Trail Crest pass", "99 Switchbacks"],
    externalUrl: "https://www.recreation.gov/permits/233260",
  },
  {
    id: "jmt",
    name: "John Muir Trail (JMT)",
    region: "yosemite-sierra",
    state: "CA",
    parkUnit: "Yosemite to Sequoia",
    difficulty: "extreme",
    type: "thru-hike",
    ecosystem: "alpine",
    lengthMiles: 211,
    elevationGainFt: 47000,
    trailhead: { lat: 37.733, lng: -119.5575 },
    permitRequired: true,
    bestSeasons: ["summer"],
    description:
      "211 miles of high Sierra grandeur from Yosemite Valley to Mt Whitney's summit. Crosses 8 mountain passes above 11,000 ft and traverses three national parks. The premier thru-hike in the American West.",
    highlights: ["Donohue Pass", "Evolution Valley", "Forester Pass (highest point on PCT)", "Whitney summit finish"],
  },
  {
    id: "rae-lakes",
    name: "Rae Lakes Loop",
    region: "yosemite-sierra",
    state: "CA",
    parkUnit: "Kings Canyon National Park",
    difficulty: "hard",
    type: "multi-day",
    ecosystem: "alpine",
    lengthMiles: 41,
    elevationGainFt: 6900,
    trailhead: { lat: 36.7944, lng: -118.5836 },
    permitRequired: true,
    bestSeasons: ["summer", "fall"],
    description:
      "A classic 4–5 day Sierra backpacking loop through painted granite basins, alpine meadows, and a chain of cobalt lakes beneath the Painted Lady. Glen Pass at 11,978 ft is the crux.",
    highlights: ["Rae Lakes basin", "Glen Pass crossing", "Mist Falls"],
  },
  {
    id: "tahoe-rim",
    name: "Tahoe Rim Trail",
    region: "yosemite-sierra",
    state: "CA",
    parkUnit: "Lake Tahoe Basin",
    difficulty: "hard",
    type: "thru-hike",
    ecosystem: "subalpine",
    lengthMiles: 165,
    elevationGainFt: 24400,
    trailhead: { lat: 39.305, lng: -119.8941 },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "A 165-mile loop circling Lake Tahoe through six wilderness areas and three national forests. Average 8,000 ft elevation with constant lake views. Typically completed in 10–14 days or section-hiked.",
    highlights: ["Desolation Wilderness", "Mt Rose summit", "Continuous Tahoe views"],
  },

  // ========== Mt Rainier ==========
  {
    id: "wonderland",
    name: "Wonderland Trail",
    region: "rainier",
    state: "WA",
    parkUnit: "Mt Rainier National Park",
    difficulty: "extreme",
    type: "thru-hike",
    ecosystem: "subalpine",
    lengthMiles: 93,
    elevationGainFt: 22000,
    trailhead: { lat: 46.7506, lng: -121.8094 },
    permitRequired: true,
    bestSeasons: ["summer"],
    description:
      "A 93-mile loop entirely circling Mt Rainier — the most consistently spectacular thru-hike in the Pacific Northwest. Crosses every ecosystem on the mountain. 10–14 days; permit lottery is competitive.",
    highlights: ["Spray Park wildflowers", "Indian Bar", "Summerland", "Continuous Rainier views"],
    externalUrl: "https://www.nps.gov/mora/planyourvisit/the-wonderland-trail.htm",
  },
  {
    id: "skyline-paradise",
    name: "Skyline Trail (Paradise)",
    region: "rainier",
    state: "WA",
    parkUnit: "Mt Rainier National Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "subalpine",
    lengthMiles: 5.5,
    elevationGainFt: 1700,
    trailhead: { lat: 46.7864, lng: -121.7355 },
    permitRequired: false,
    bestSeasons: ["summer"],
    description:
      "The crown-jewel day hike from Paradise. Climbs through wildflower meadows to Panorama Point, framed by glaciers and the Tatoosh Range. Peak bloom in late July.",
    highlights: ["Myrtle Falls", "Panorama Point", "Nisqually Glacier overlook"],
  },
  {
    id: "naches-peak",
    name: "Naches Peak Loop",
    region: "rainier",
    state: "WA",
    parkUnit: "Mt Rainier National Park",
    difficulty: "easy",
    type: "day",
    ecosystem: "subalpine",
    lengthMiles: 3.2,
    elevationGainFt: 600,
    trailhead: { lat: 46.8717, lng: -121.5197 },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "A short, family-friendly loop at Chinook Pass that delivers maximum scenery per step: alpine tarns, wildflowers, and a head-on Rainier portrait.",
    highlights: ["Tipsoo Lake reflection", "PCT segment", "Fall huckleberries"],
  },
  {
    id: "burroughs",
    name: "Burroughs Mountain",
    region: "rainier",
    state: "WA",
    parkUnit: "Mt Rainier National Park",
    difficulty: "hard",
    type: "day",
    ecosystem: "alpine",
    lengthMiles: 9,
    elevationGainFt: 2500,
    trailhead: { lat: 46.9145, lng: -121.6428 },
    permitRequired: false,
    bestSeasons: ["summer"],
    description:
      "An arctic-tundra plateau on Rainier's NE flank. Three Burroughs summits get progressively closer to the Emmons Glacier. The closest you can stand to the mountain without a rope.",
    highlights: ["Emmons Glacier overlook", "Tundra ecosystem", "Frozen Lake"],
  },
  {
    id: "tolmie-peak",
    name: "Tolmie Peak Lookout",
    region: "rainier",
    state: "WA",
    parkUnit: "Mt Rainier National Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "subalpine",
    lengthMiles: 6.5,
    elevationGainFt: 1100,
    trailhead: { lat: 46.9337, lng: -121.8631 },
    permitRequired: false,
    bestSeasons: ["summer"],
    description:
      "A historic fire lookout perched above Eunice Lake with a postcard view of Rainier. The drive to Mowich Lake is bumpy gravel — and worth every mile.",
    highlights: ["Eunice Lake", "Restored 1933 fire lookout", "Mowich Lake"],
  },

  // ========== Olympic NP ==========
  {
    id: "hall-of-mosses",
    name: "Hall of Mosses (Hoh Rainforest)",
    region: "olympic",
    state: "WA",
    parkUnit: "Olympic National Park",
    difficulty: "easy",
    type: "day",
    ecosystem: "rainforest",
    lengthMiles: 0.8,
    elevationGainFt: 100,
    trailhead: { lat: 47.8606, lng: -123.9352 },
    permitRequired: false,
    bestSeasons: ["spring", "summer", "fall", "winter"],
    description:
      "An otherworldly stroll through one of the few temperate rainforests on Earth. Big-leaf maples drip with club moss; everything glows green.",
    highlights: ["Old-growth Sitka spruce", "Moss-draped maples", "Year-round trail"],
  },
  {
    id: "hurricane-hill",
    name: "Hurricane Hill",
    region: "olympic",
    state: "WA",
    parkUnit: "Olympic National Park",
    difficulty: "easy",
    type: "day",
    ecosystem: "subalpine",
    lengthMiles: 3.2,
    elevationGainFt: 700,
    trailhead: { lat: 47.9778, lng: -123.5183 },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "A paved-then-dirt path to a 5,757-ft summit with views from the Olympic interior to Vancouver Island. Black-tailed deer and marmots are routine sightings.",
    highlights: ["Strait of Juan de Fuca view", "Mt Olympus skyline", "Wildflowers"],
  },
  {
    id: "storm-king",
    name: "Mt Storm King",
    region: "olympic",
    state: "WA",
    parkUnit: "Olympic National Park",
    difficulty: "hard",
    type: "day",
    ecosystem: "rainforest",
    lengthMiles: 4.1,
    elevationGainFt: 2100,
    trailhead: { lat: 48.0589, lng: -123.7886 },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "A brutally steep scramble above Lake Crescent that ends at fixed ropes climbing onto a knife-edge summit. The view straight down 2,000 ft to the lake is unforgettable.",
    highlights: ["Lake Crescent overlook", "Rope-assisted scramble", "Marymere Falls add-on"],
  },
  {
    id: "shi-shi",
    name: "Shi Shi Beach + Point of the Arches",
    region: "olympic",
    state: "WA",
    parkUnit: "Olympic National Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "coastal",
    lengthMiles: 8,
    elevationGainFt: 200,
    trailhead: { lat: 48.2792, lng: -124.6794 },
    permitRequired: true,
    bestSeasons: ["spring", "summer", "fall"],
    description:
      "Wild Pacific coast at its rawest: a muddy boardwalk forest gives way to two miles of sand and ends at the sea-stack labyrinth of Point of the Arches. Tide-aware planning required.",
    highlights: ["Sea stacks", "Tidepools", "Beach camping"],
  },
  {
    id: "high-divide",
    name: "High Divide / Seven Lakes Basin Loop",
    region: "olympic",
    state: "WA",
    parkUnit: "Olympic National Park",
    difficulty: "hard",
    type: "multi-day",
    ecosystem: "subalpine",
    lengthMiles: 19,
    elevationGainFt: 3500,
    trailhead: { lat: 47.9542, lng: -123.8344 },
    permitRequired: true,
    bestSeasons: ["summer"],
    description:
      "Olympic NP's premier backpacking loop: cobalt lake basins, a high ridge facing the Mt Olympus icefields, and constant black bear sightings in late summer.",
    highlights: ["Mt Olympus glacier views", "Heart Lake", "Bogachiel Peak"],
  },
  {
    id: "sol-duc-falls",
    name: "Sol Duc Falls",
    region: "olympic",
    state: "WA",
    parkUnit: "Olympic National Park",
    difficulty: "easy",
    type: "day",
    ecosystem: "rainforest",
    lengthMiles: 1.6,
    elevationGainFt: 200,
    trailhead: { lat: 47.9542, lng: -123.8344 },
    permitRequired: false,
    bestSeasons: ["spring", "summer", "fall", "winter"],
    description:
      "A flat, family-friendly walk through old-growth Douglas fir to a triple-channel waterfall plunging into a mossy gorge. Especially beautiful in winter when accessible.",
    highlights: ["Triple-cascade falls", "Old-growth forest", "Year-round trail"],
  },

  // ========== North Cascades ==========
  {
    id: "maple-pass",
    name: "Maple Pass Loop",
    region: "north-cascades",
    state: "WA",
    parkUnit: "Okanogan-Wenatchee National Forest",
    difficulty: "moderate",
    type: "day",
    ecosystem: "subalpine",
    lengthMiles: 7.2,
    elevationGainFt: 2000,
    trailhead: { lat: 48.5167, lng: -120.7383 },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "Widely considered the best day-hike loop in the North Cascades. A ridge walk with views into Lake Ann, Heather Pass, and a sea of jagged peaks. Larch gold in late September.",
    highlights: ["Larch trees in fall", "Lake Ann overlook", "Heather Pass ridgeline"],
  },
  {
    id: "cascade-pass",
    name: "Cascade Pass + Sahale Arm",
    region: "north-cascades",
    state: "WA",
    parkUnit: "North Cascades National Park",
    difficulty: "hard",
    type: "day",
    ecosystem: "alpine",
    lengthMiles: 12,
    elevationGainFt: 4000,
    trailhead: { lat: 48.4744, lng: -121.0759 },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "From a saddle deep in the North Cascades, climb a knife ridge to Sahale Glacier Camp at 7,600 ft — surrounded on all sides by the most rugged peaks in the lower 48.",
    highlights: ["Sahale Glacier", "Mountain goats", "Most dramatic skyline in the range"],
  },
  {
    id: "blue-lake",
    name: "Blue Lake (Washington Pass)",
    region: "north-cascades",
    state: "WA",
    parkUnit: "Okanogan-Wenatchee National Forest",
    difficulty: "easy",
    type: "day",
    ecosystem: "subalpine",
    lengthMiles: 4.4,
    elevationGainFt: 1100,
    trailhead: { lat: 48.5215, lng: -120.67 },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "A short approach to a turquoise alpine lake surrounded by Liberty Bell, Early Winter Spires, and (in autumn) golden larches. The lowest-effort big payoff in the Cascades.",
    highlights: ["Liberty Bell spires", "Larches in October", "Beginner-friendly alpine"],
  },
  {
    id: "hidden-lake",
    name: "Hidden Lake Lookout",
    region: "north-cascades",
    state: "WA",
    parkUnit: "Mt Baker-Snoqualmie National Forest",
    difficulty: "hard",
    type: "day",
    ecosystem: "alpine",
    lengthMiles: 8,
    elevationGainFt: 3300,
    trailhead: { lat: 48.5066, lng: -121.2076 },
    permitRequired: false,
    bestSeasons: ["summer"],
    description:
      "A rugged climb to a historic 1931 fire lookout perched at 6,890 ft on a granite spike — with one of the most photographed views in Washington.",
    highlights: ["1931 fire lookout", "Granite ridge scramble", "Hidden Lake view"],
  },
  {
    id: "heliotrope",
    name: "Heliotrope Ridge (Mt Baker)",
    region: "north-cascades",
    state: "WA",
    parkUnit: "Mt Baker-Snoqualmie National Forest",
    difficulty: "moderate",
    type: "day",
    ecosystem: "alpine",
    lengthMiles: 5.5,
    elevationGainFt: 1900,
    trailhead: { lat: 48.7864, lng: -121.8453 },
    permitRequired: false,
    bestSeasons: ["summer"],
    description:
      "A climber's approach trail that gets non-climbers within 100 yards of the Coleman Glacier. Crevasse views without ice axes.",
    highlights: ["Coleman Glacier toe", "Mt Baker close-up", "Stream crossings"],
  },

  // ========== Oregon Cascades + Gorge ==========
  {
    id: "timberline",
    name: "Timberline Trail (Mt Hood)",
    region: "oregon",
    state: "OR",
    parkUnit: "Mt Hood National Forest",
    difficulty: "hard",
    type: "multi-day",
    ecosystem: "subalpine",
    lengthMiles: 41,
    elevationGainFt: 9000,
    trailhead: { lat: 45.3309, lng: -121.7113 },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "A 41-mile loop circumnavigating Mt Hood — Oregon's signature multi-day backpack. Glacial river fords, wildflower meadows, and a continuous 11,250-ft mountain overhead.",
    highlights: ["Ramona Falls", "Eliot Glacier crossing", "Paradise Park wildflowers"],
  },
  {
    id: "garfield-peak",
    name: "Garfield Peak (Crater Lake)",
    region: "oregon",
    state: "OR",
    parkUnit: "Crater Lake National Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "volcanic",
    lengthMiles: 3.6,
    elevationGainFt: 1000,
    trailhead: { lat: 42.9119, lng: -122.1456 },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "The best Crater Lake viewpoint without a backcountry permit. Climbs from Rim Village to an 8,054-ft summit with the entire caldera at your feet.",
    highlights: ["Caldera-top panorama", "Wizard Island view", "Klamath Basin distant view"],
  },
  {
    id: "south-sister",
    name: "South Sister Summit",
    region: "oregon",
    state: "OR",
    parkUnit: "Three Sisters Wilderness",
    difficulty: "hard",
    type: "day",
    ecosystem: "volcanic",
    lengthMiles: 12,
    elevationGainFt: 4900,
    trailhead: { lat: 44.0317, lng: -121.7572 },
    permitRequired: true,
    bestSeasons: ["summer"],
    description:
      "A nontechnical climb to the 10,358-ft summit of Oregon's third-tallest peak. Volcanic gravel, a summit crater lake, and views of the entire Cascades chain.",
    highlights: ["Summit crater lake", "Middle and North Sister profile", "Lewis Glacier"],
  },
  {
    id: "eagle-creek",
    name: "Eagle Creek to Tunnel Falls",
    region: "oregon",
    state: "OR",
    parkUnit: "Columbia River Gorge",
    difficulty: "moderate",
    type: "day",
    ecosystem: "gorge",
    lengthMiles: 12,
    elevationGainFt: 1640,
    trailhead: { lat: 45.6361, lng: -121.9197 },
    permitRequired: false,
    bestSeasons: ["spring", "fall"],
    description:
      "A waterfall-after-waterfall trail along a basalt-walled creek, climaxing with a tunnel cut behind 175-ft Tunnel Falls. Cliff-edge trail with cable handholds — not for the height-averse.",
    highlights: ["Punchbowl Falls", "High Bridge", "Walk behind Tunnel Falls"],
  },
  {
    id: "multnomah-wahkeena",
    name: "Multnomah-Wahkeena Falls Loop",
    region: "oregon",
    state: "OR",
    parkUnit: "Columbia River Gorge",
    difficulty: "moderate",
    type: "day",
    ecosystem: "gorge",
    lengthMiles: 5,
    elevationGainFt: 1600,
    trailhead: { lat: 45.576, lng: -122.1158 },
    permitRequired: false,
    bestSeasons: ["spring", "fall", "winter"],
    description:
      "Connects Oregon's two most famous waterfalls in a forested loop. Multnomah Falls is 620 ft of two-tier drama; Wahkeena adds a ribbon cascade behind it.",
    highlights: ["Multnomah Falls", "Wahkeena Falls", "Benson Bridge"],
  },
  {
    id: "smith-rock",
    name: "Misery Ridge Loop (Smith Rock)",
    region: "oregon",
    state: "OR",
    parkUnit: "Smith Rock State Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "desert",
    lengthMiles: 3.7,
    elevationGainFt: 1100,
    trailhead: { lat: 44.3679, lng: -121.1395 },
    permitRequired: false,
    bestSeasons: ["spring", "fall"],
    description:
      "A short, intensely scenic loop above the Crooked River canyon. Rock climbers hang from every overhang — Smith Rock is the birthplace of American sport climbing.",
    highlights: ["Monkey Face spire", "Crooked River canyon", "Rock climbers everywhere"],
  },

  // ========== Northern California ==========
  {
    id: "lassen-peak",
    name: "Lassen Peak",
    region: "norcal",
    state: "CA",
    parkUnit: "Lassen Volcanic National Park",
    difficulty: "hard",
    type: "day",
    ecosystem: "volcanic",
    lengthMiles: 5,
    elevationGainFt: 2000,
    trailhead: { lat: 40.4732, lng: -121.5036 },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "Climb to the 10,457-ft summit of one of America's most recently active volcanoes (1915). Views of Mt Shasta, the Sierra, and the steaming hydrothermal areas below.",
    highlights: ["Active volcano summit", "Mt Shasta view", "Steam vents"],
  },
  {
    id: "bumpass-hell",
    name: "Bumpass Hell (Lassen)",
    region: "norcal",
    state: "CA",
    parkUnit: "Lassen Volcanic National Park",
    difficulty: "easy",
    type: "day",
    ecosystem: "volcanic",
    lengthMiles: 3,
    elevationGainFt: 500,
    trailhead: { lat: 40.4565, lng: -121.5028 },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "A boardwalk through the largest hydrothermal area in the park. Boiling mud pots, fumaroles, and turquoise pools — Yellowstone, but with no crowds.",
    highlights: ["Boiling mud pots", "Fumaroles", "Boardwalk through hot springs"],
  },
  {
    id: "fern-canyon",
    name: "Fern Canyon Loop (Prairie Creek)",
    region: "norcal",
    state: "CA",
    parkUnit: "Prairie Creek Redwoods State Park",
    difficulty: "easy",
    type: "day",
    ecosystem: "redwood",
    lengthMiles: 1,
    elevationGainFt: 100,
    trailhead: { lat: 41.4002, lng: -124.0653 },
    permitRequired: true,
    bestSeasons: ["summer", "fall"],
    description:
      "A 50-foot-deep canyon walled in seven species of fern. Filmed for Jurassic Park 2. Timed-entry permit required May–September; expect to wade.",
    highlights: ["Fern-covered canyon walls", "Jurassic Park filming location", "Coastal redwoods nearby"],
  },
  {
    id: "lost-coast",
    name: "Lost Coast Trail",
    region: "norcal",
    state: "CA",
    parkUnit: "King Range National Conservation Area",
    difficulty: "hard",
    type: "multi-day",
    ecosystem: "coastal",
    lengthMiles: 25,
    elevationGainFt: 1500,
    trailhead: { lat: 40.2911, lng: -124.3528 },
    permitRequired: true,
    bestSeasons: ["spring", "fall"],
    description:
      "California's only true wilderness coastline — 25 miles of black-sand beaches between two roads. Tide-dependent: two impassable zones must be crossed at low water. Bear cans required.",
    highlights: ["Black sand beaches", "Tide-required passages", "Roosevelt elk and seals"],
  },

  // ========== Southern CA + Desert ==========
  {
    id: "ryan-mountain",
    name: "Ryan Mountain (Joshua Tree)",
    region: "socal-desert",
    state: "CA",
    parkUnit: "Joshua Tree National Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "desert",
    lengthMiles: 3,
    elevationGainFt: 1000,
    trailhead: { lat: 33.9852, lng: -116.133 },
    permitRequired: false,
    bestSeasons: ["fall", "winter", "spring"],
    description:
      "A short, steep ascent to the centerpiece summit of Joshua Tree NP. The 360° view spans the Wonderland of Rocks, the Salton Sea, and (on clear days) the snowcapped San Gorgonio range.",
    highlights: ["Wonderland of Rocks view", "Sunrise/sunset hike", "San Gorgonio in winter"],
  },
  {
    id: "telescope-peak",
    name: "Telescope Peak (Death Valley)",
    region: "socal-desert",
    state: "CA",
    parkUnit: "Death Valley National Park",
    difficulty: "hard",
    type: "day",
    ecosystem: "desert",
    lengthMiles: 14,
    elevationGainFt: 3000,
    trailhead: { lat: 36.2306, lng: -117.0644 },
    permitRequired: false,
    bestSeasons: ["spring", "fall"],
    description:
      "The highest point in Death Valley NP at 11,049 ft, named for its commanding view of both Badwater (-282 ft) and Mt Whitney (14,505 ft) on the same horizon.",
    highlights: ["Bristlecone pines", "Badwater + Whitney visible together", "Snow possible into June"],
  },
  {
    id: "san-jacinto",
    name: "Mt San Jacinto via Tram",
    region: "socal-desert",
    state: "CA",
    parkUnit: "San Jacinto State Wilderness",
    difficulty: "moderate",
    type: "day",
    ecosystem: "alpine",
    lengthMiles: 11,
    elevationGainFt: 2300,
    trailhead: { lat: 33.8125, lng: -116.6402 },
    permitRequired: false,
    bestSeasons: ["spring", "summer", "fall"],
    description:
      "Ride the Palm Springs Aerial Tramway from desert floor to 8,500 ft, then hike 5.5 miles to a 10,834-ft summit overlooking Coachella Valley. The biggest single-day vertical relief in the lower 48.",
    highlights: ["Aerial tram approach", "Round Valley meadow", "Summit boulder scramble"],
  },
  {
    id: "mt-baldy",
    name: "Mt Baldy (Devil's Backbone)",
    region: "socal-desert",
    state: "CA",
    parkUnit: "Angeles National Forest",
    difficulty: "hard",
    type: "day",
    ecosystem: "chaparral",
    lengthMiles: 11,
    elevationGainFt: 3900,
    trailhead: { lat: 34.2606, lng: -117.6314 },
    permitRequired: false,
    bestSeasons: ["spring", "summer", "fall"],
    description:
      "LA's home mountain at 10,064 ft. The Devil's Backbone ridge is the classic loop — narrow, exposed, and topping out with views from Catalina to the Mojave.",
    highlights: ["Devil's Backbone ridge", "Catalina Island view", "Bighorn sheep"],
  },
  {
    id: "smugglers",
    name: "Smugglers Cove (Channel Islands)",
    region: "socal-desert",
    state: "CA",
    parkUnit: "Channel Islands National Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "coastal",
    lengthMiles: 7.5,
    elevationGainFt: 1000,
    trailhead: { lat: 34.0489, lng: -119.5572 },
    permitRequired: false,
    bestSeasons: ["spring", "fall", "winter"],
    description:
      "A boat ride from Ventura, then a coastal traverse on Santa Cruz Island to a quiet cove. Endemic island foxes, sea cliffs, and zero crowds make this America's least-visited NP shine.",
    highlights: ["Island fox sightings", "Sea-cliff vistas", "Olive grove ruins at Smugglers"],
  },

  // ========== Big Sur + Bay Area ==========
  {
    id: "ewoldsen",
    name: "Ewoldsen Trail (McWay Falls)",
    region: "bigsur-bay",
    state: "CA",
    parkUnit: "Julia Pfeiffer Burns State Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "redwood",
    lengthMiles: 4.5,
    elevationGainFt: 1500,
    trailhead: { lat: 36.1574, lng: -121.6707 },
    permitRequired: false,
    bestSeasons: ["spring", "summer", "fall", "winter"],
    description:
      "A redwood-canyon loop above the Big Sur coast, paired with the iconic McWay Falls overlook — an 80-ft waterfall plunging directly onto the beach.",
    highlights: ["McWay Falls overlook", "Redwood canyon", "Pacific Ocean panorama"],
  },
  {
    id: "tomales-point",
    name: "Tomales Point",
    region: "bigsur-bay",
    state: "CA",
    parkUnit: "Point Reyes National Seashore",
    difficulty: "moderate",
    type: "day",
    ecosystem: "coastal",
    lengthMiles: 9.5,
    elevationGainFt: 1100,
    trailhead: { lat: 38.1873, lng: -122.9495 },
    permitRequired: false,
    bestSeasons: ["spring", "fall", "winter"],
    description:
      "A windswept ridge to the northern tip of Point Reyes, walking through the Tule Elk Reserve. Hundreds of elk, two bays, and one lighthouse on the horizon.",
    highlights: ["Tule elk herd", "Ocean and bay simultaneously", "Wildflowers in spring"],
  },
  {
    id: "alamere",
    name: "Alamere Falls (Coast Trail)",
    region: "bigsur-bay",
    state: "CA",
    parkUnit: "Point Reyes National Seashore",
    difficulty: "moderate",
    type: "day",
    ecosystem: "coastal",
    lengthMiles: 13,
    elevationGainFt: 1300,
    trailhead: { lat: 37.9368, lng: -122.747 },
    permitRequired: false,
    bestSeasons: ["winter", "spring"],
    description:
      "A rare 'tidefall' that drops directly onto the beach. The 13-mile coastal trail passes hidden lakes and cliff-edge prairie before the final scramble down to the falls.",
    highlights: ["Tidefall onto beach", "Bass Lake swim", "Bobcat sightings"],
  },
  {
    id: "mt-tam",
    name: "Mt Tamalpais East Peak Loop",
    region: "bigsur-bay",
    state: "CA",
    parkUnit: "Mt Tamalpais State Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "chaparral",
    lengthMiles: 6,
    elevationGainFt: 1700,
    trailhead: { lat: 37.9286, lng: -122.5797 },
    permitRequired: false,
    bestSeasons: ["spring", "fall", "winter"],
    description:
      "The Bay Area's signature mountain. The East Peak summit looks over San Francisco, the Farallon Islands, and the Sierra crest on rare crystal days.",
    highlights: ["SF skyline view", "Old Railroad Grade", "Verna Dunshee summit loop"],
  },
  {
    id: "andrew-molera",
    name: "Andrew Molera Headlands Loop",
    region: "bigsur-bay",
    state: "CA",
    parkUnit: "Andrew Molera State Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "coastal",
    lengthMiles: 8,
    elevationGainFt: 1100,
    trailhead: { lat: 36.2867, lng: -121.8461 },
    permitRequired: false,
    bestSeasons: ["spring", "fall", "winter"],
    description:
      "Big Sur's best loop hike: bluff-top trails over crashing surf, a hidden beach, and a riverfront return through cottonwoods.",
    highlights: ["Bluff-top ocean views", "Molera Beach", "Big Sur River mouth"],
  },
  {
    id: "mt-diablo",
    name: "Mary Bowerman Summit Loop",
    region: "bigsur-bay",
    state: "CA",
    parkUnit: "Mt Diablo State Park",
    difficulty: "easy",
    type: "day",
    ecosystem: "chaparral",
    lengthMiles: 0.7,
    elevationGainFt: 250,
    trailhead: { lat: 37.8829, lng: -121.9148, name: "Summit parking" },
    permitRequired: false,
    bestSeasons: ["spring", "fall", "winter"],
    description:
      "A short interpretive loop right around the 3,849-ft summit — one of the largest viewable areas of any peak in North America. On clear days you'll see from the Sierra crest to the Farallon Islands.",
    highlights: ["35-state-equivalent visible area", "Wildflower super-blooms in spring", "Summit observation deck"],
    parking:
      "Summit parking lot at the very top of South Gate Road. State park entry $10/vehicle. Small lot fills weekend midday — arrive before 11 a.m. or after 3 p.m.",
  },
  {
    id: "high-peaks-pinnacles",
    name: "High Peaks Trail (Pinnacles)",
    region: "bigsur-bay",
    state: "CA",
    parkUnit: "Pinnacles National Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "chaparral",
    lengthMiles: 6.7,
    elevationGainFt: 1500,
    trailhead: { lat: 36.4906, lng: -121.1825 },
    permitRequired: false,
    bestSeasons: ["winter", "spring", "fall"],
    description:
      "Steel handholds carved into volcanic spires take you through one of the West's most reliable California condor habitats. America's youngest national park.",
    highlights: ["California condor sightings", "Stairs cut into rock", "Talus caves nearby"],
  },

  // ========== Iconic Thru-Hikes / Misc ==========
  {
    id: "pct",
    name: "Pacific Crest Trail (PCT)",
    region: "thru-hike",
    state: "Multi",
    parkUnit: "Mexico to Canada",
    difficulty: "extreme",
    type: "thru-hike",
    ecosystem: "alpine",
    lengthMiles: 2650,
    elevationGainFt: 489000,
    trailhead: { lat: 32.5959, lng: -116.467 },
    permitRequired: true,
    bestSeasons: ["spring", "summer", "fall"],
    description:
      "2,650 miles from Mexico to Canada through every major mountain range on the West Coast. A 5–6 month commitment that has become a generational rite of passage. Long-distance permit issued by lottery.",
    highlights: ["3 states, 25 national forests, 7 national parks", "From desert to glaciers", "The most photographed thru-hike in the world"],
    externalUrl: "https://www.pcta.org/discover-the-trail/permits/long-distance-permit/",
  },
  {
    id: "mt-si",
    name: "Mt Si",
    region: "north-cascades",
    state: "WA",
    parkUnit: "Mt Si Natural Resources Conservation Area",
    difficulty: "hard",
    type: "day",
    ecosystem: "rainforest",
    lengthMiles: 8,
    elevationGainFt: 3150,
    trailhead: { lat: 47.4885, lng: -121.7228 },
    permitRequired: false,
    bestSeasons: ["spring", "summer", "fall"],
    description:
      "Seattle's training-mountain-of-record. A relentless forested climb 30 minutes from downtown, ending at a haystack summit overlooking the Snoqualmie Valley.",
    highlights: ["Seattle skyline view", "Cascades to Olympic panorama", "Year-round access"],
  },

  // ========== Sequoia + Kings Canyon ==========
  {
    id: "mist-falls",
    name: "Mist Falls",
    region: "yosemite-sierra",
    state: "CA",
    parkUnit: "Kings Canyon National Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "alpine",
    lengthMiles: 8.0,
    elevationGainFt: 800,
    trailhead: { lat: 36.7949, lng: -118.5833, name: "Roads End" },
    permitRequired: false,
    bestSeasons: ["spring", "summer", "fall"],
    description:
      "A long flat walk through Paradise Valley along the Kings River, climaxing at a thunderous 100-ft cataract that throws spray across the trail in early summer.",
    highlights: ["Kings River canyon", "100-ft Mist Falls", "Granite domes overhead"],
    parking:
      "Roads End trailhead lot at the eastern terminus of Highway 180. Park entrance fee $35/vehicle (7 days). Lot fills by 9 a.m. summer weekends; arrive early or take the free Cedar Grove shuttle.",
  },
  {
    id: "lakes-trail",
    name: "Lakes Trail to Pear Lake",
    region: "yosemite-sierra",
    state: "CA",
    parkUnit: "Sequoia National Park",
    difficulty: "hard",
    type: "day",
    ecosystem: "alpine",
    lengthMiles: 12.6,
    elevationGainFt: 2500,
    trailhead: { lat: 36.5969, lng: -118.7283, name: "Wolverton" },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "A high-Sierra classic from Wolverton up the Watchtower cliff to a chain of cirque lakes — Heather, Aster, Emerald, finally Pear — set under granite walls.",
    highlights: ["Watchtower cliff edge", "Four cirque lakes", "Pear Lake granite bowl"],
    parking:
      "Wolverton parking lot off Generals Highway. Park entrance fee $35/vehicle (7 days). Plenty of capacity but the road closes seasonally — typically Nov–May with snow.",
  },
  {
    id: "moro-rock",
    name: "Moro Rock",
    region: "yosemite-sierra",
    state: "CA",
    parkUnit: "Sequoia National Park",
    difficulty: "easy",
    type: "day",
    ecosystem: "alpine",
    lengthMiles: 0.5,
    elevationGainFt: 300,
    trailhead: { lat: 36.547, lng: -118.7656, name: "Moro Rock parking" },
    permitRequired: false,
    bestSeasons: ["spring", "summer", "fall"],
    description:
      "A 350-step staircase carved into a granite dome, leading to a vertiginous 6,725-ft summit with the Great Western Divide spread out to the east.",
    highlights: ["Carved stone staircase", "Great Western Divide panorama", "Sunset hike favorite"],
    parking:
      "Small lot at the base of the dome, off Crescent Meadow Road. In summer (late May–Sept) the road is closed to private vehicles 9–4; use the free shuttle from Giant Forest Museum.",
  },
  {
    id: "tokopah-falls",
    name: "Tokopah Falls",
    region: "yosemite-sierra",
    state: "CA",
    parkUnit: "Sequoia National Park",
    difficulty: "easy",
    type: "day",
    ecosystem: "subalpine",
    lengthMiles: 4.0,
    elevationGainFt: 600,
    trailhead: { lat: 36.6041, lng: -118.7314, name: "Lodgepole Campground" },
    permitRequired: false,
    bestSeasons: ["spring", "summer"],
    description:
      "Follow the Marble Fork through pine forest to the foot of a 1,200-ft cascade tumbling off a granite headwall — peak flow late May through June.",
    highlights: ["Marble Fork canyon", "1,200-ft Tokopah Falls", "Marmots in the talus"],
    parking:
      "Lodgepole Campground day-use lot. Park entrance fee $35/vehicle. Walk through the campground to the trailhead at the river bridge.",
  },

  // ========== Mt Hood + Oregon Cascades ==========
  {
    id: "tom-dick-harry",
    name: "Tom, Dick & Harry Mountain",
    region: "oregon",
    state: "OR",
    parkUnit: "Mt Hood National Forest",
    difficulty: "moderate",
    type: "day",
    ecosystem: "subalpine",
    lengthMiles: 7.2,
    elevationGainFt: 1750,
    trailhead: { lat: 45.3001, lng: -121.7758, name: "Mirror Lake trailhead" },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "Past Mirror Lake's iconic Mt Hood reflection, then up a forested ridge to a three-summit traverse with the volcano filling the eastern sky.",
    highlights: ["Mirror Lake reflection", "Mt Hood face-on view", "Three rocky summits"],
    parking:
      "Mirror Lake Trailhead lot off Highway 26. Northwest Forest Pass required ($5/day or $30/year). Lot fills by 9 a.m. weekends — overflow parking 0.3 mi east.",
  },
  {
    id: "mcneil-point",
    name: "McNeil Point",
    region: "oregon",
    state: "OR",
    parkUnit: "Mt Hood National Forest",
    difficulty: "hard",
    type: "day",
    ecosystem: "alpine",
    lengthMiles: 9.0,
    elevationGainFt: 2400,
    trailhead: { lat: 45.4054, lng: -121.7866, name: "Top Spur trailhead" },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "From the Top Spur trailhead, climb meadows of avalanche lily and lupine to a stone shelter at 6,100 ft, perched on Mt Hood's northwest shoulder above the Sandy Glacier.",
    highlights: ["Bald Mountain meadows", "CCC stone shelter", "Sandy Glacier overlook"],
    parking:
      "Top Spur trailhead lot at the end of FS Road 1828, gravel and rough — sedans manage in dry weather. Northwest Forest Pass required. Holds about 15 cars; fills by 8 a.m. summer weekends.",
  },
  {
    id: "tamanawas-falls",
    name: "Tamanawas Falls",
    region: "oregon",
    state: "OR",
    parkUnit: "Mt Hood National Forest",
    difficulty: "easy",
    type: "day",
    ecosystem: "rainforest",
    lengthMiles: 3.6,
    elevationGainFt: 500,
    trailhead: { lat: 45.3987, lng: -121.5729, name: "Highway 35 pullout" },
    permitRequired: false,
    bestSeasons: ["spring", "summer", "fall"],
    description:
      "A gentle forest walk along Cold Spring Creek to the base of a wide 110-ft curtain of water — you can scramble behind the falls when flow is moderate.",
    highlights: ["Cold Spring Creek", "Walk behind the falls", "Old-growth forest"],
    parking:
      "Roadside pullout on Highway 35, mile 73 (across from Sherwood Campground). Free, no pass required. Holds about 25 cars.",
  },
  {
    id: "cooper-spur",
    name: "Cooper Spur",
    region: "oregon",
    state: "OR",
    parkUnit: "Mt Hood National Forest",
    difficulty: "hard",
    type: "day",
    ecosystem: "alpine",
    lengthMiles: 7.0,
    elevationGainFt: 2800,
    trailhead: { lat: 45.4044, lng: -121.6829, name: "Cloud Cap Saddle" },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "The highest non-technical hike on Mt Hood — climb the volcano's northeast shoulder to 8,500 ft with the Eliot Glacier breaking off below your boots.",
    highlights: ["Tilly Jane shelter", "Eliot Glacier crevasses", "8,500-ft turnaround stone"],
    parking:
      "Cloud Cap Saddle trailhead at the end of FS Road 3512, a dirt washboard — 25 minutes slow drive from Highway 35. Northwest Forest Pass required. Closes with first snow (Oct–June).",
  },

  // ========== Mt Lassen ==========
  {
    id: "cinder-cone",
    name: "Cinder Cone Trail",
    region: "norcal",
    state: "CA",
    parkUnit: "Lassen Volcanic National Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "volcanic",
    lengthMiles: 4.0,
    elevationGainFt: 850,
    trailhead: { lat: 40.5544, lng: -121.2935, name: "Butte Lake" },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "Slog up the loose ash side of a perfect 700-ft cinder cone, then circle the rim above the multicolored Painted Dunes and the Fantastic Lava Beds.",
    highlights: ["Painted Dunes overlook", "Fantastic Lava Beds", "Two crater rims to walk"],
    parking:
      "Butte Lake Campground day-use lot, end of FS Road 32N21 (6 mi gravel from Highway 44). Park entrance fee $30/vehicle. Holds 30+ cars, rarely full.",
  },

  // ========== Joshua Tree + SoCal Desert ==========
  {
    id: "hidden-valley",
    name: "Hidden Valley Loop",
    region: "socal-desert",
    state: "CA",
    parkUnit: "Joshua Tree National Park",
    difficulty: "easy",
    type: "day",
    ecosystem: "desert",
    lengthMiles: 1.0,
    elevationGainFt: 100,
    trailhead: { lat: 33.9979, lng: -116.1683, name: "Hidden Valley picnic area" },
    permitRequired: false,
    bestSeasons: ["fall", "winter", "spring"],
    description:
      "The classic introduction to Joshua Tree's monzogranite rockscape: a cattle-rustler's hideout enclosed by 100-ft boulder walls, threaded with bouldering problems.",
    highlights: ["Monzogranite boulder amphitheater", "World-class bouldering", "Joshua tree forest"],
    parking:
      "Hidden Valley picnic area lot off Park Boulevard. Park entrance fee $30/vehicle (7 days). Fills 9–noon on cool-season weekends; arrive early or after 2 p.m.",
  },
  {
    id: "lost-palms-oasis",
    name: "Lost Palms Oasis",
    region: "socal-desert",
    state: "CA",
    parkUnit: "Joshua Tree National Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "desert",
    lengthMiles: 7.5,
    elevationGainFt: 1000,
    trailhead: { lat: 33.7332, lng: -115.8049, name: "Cottonwood Spring" },
    permitRequired: false,
    bestSeasons: ["fall", "winter", "spring"],
    description:
      "Out through Colorado-desert washes and rocky ridges to a hidden canyon where the largest grove of native California fan palms in the park clings to a seep.",
    highlights: ["Cottonwood Spring oasis", "70+ native palms in canyon", "Rare desert bighorn sightings"],
    parking:
      "Cottonwood Spring day-use lot at the south entrance (off I-10). Park entrance fee $30/vehicle. Plenty of capacity year-round.",
  },
  {
    id: "forty-nine-palms",
    name: "49 Palms Oasis",
    region: "socal-desert",
    state: "CA",
    parkUnit: "Joshua Tree National Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "desert",
    lengthMiles: 3.0,
    elevationGainFt: 750,
    trailhead: { lat: 34.1144, lng: -116.1268, name: "49 Palms trailhead" },
    permitRequired: false,
    bestSeasons: ["fall", "winter", "spring"],
    description:
      "A stiff up-and-over the desert ridge from the Twentynine Palms suburbs, ending at a fan-palm oasis fed by a spring at the head of a rocky canyon.",
    highlights: ["Mojave-to-Colorado desert transition", "Fan palm grove", "Bighorn sheep tracks"],
    parking:
      "Small trailhead lot at the end of Canyon Road (off Highway 62 in Twentynine Palms). Free — outside the park entrance gate. Holds 20 cars; fills by 9 a.m. weekends.",
  },

  // ========== North Cascades east ==========
  {
    id: "kendall-katwalk",
    name: "Kendall Katwalk via PCT",
    region: "north-cascades",
    state: "WA",
    parkUnit: "Mt Baker–Snoqualmie National Forest",
    difficulty: "hard",
    type: "day",
    ecosystem: "subalpine",
    lengthMiles: 12.0,
    elevationGainFt: 2700,
    trailhead: { lat: 47.4275, lng: -121.4133, name: "Snoqualmie Pass PCT trailhead" },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "A long climb on the PCT to a literally chiseled traverse — the Katwalk — blasted out of a sheer granite face with the Cascades stacked behind you in every direction.",
    highlights: ["Granite-blasted Katwalk traverse", "Kendall Peak ridgeline", "Heather meadows in late summer"],
    parking:
      "PCT trailhead lot off exit 52 of I-90 (Snoqualmie Pass). Northwest Forest Pass required ($5/day). Two large lots; fills by 8 a.m. summer weekends.",
  },
  {
    id: "cutthroat-pass",
    name: "Cutthroat Pass via PCT",
    region: "north-cascades",
    state: "WA",
    parkUnit: "Okanogan-Wenatchee National Forest",
    difficulty: "hard",
    type: "day",
    ecosystem: "alpine",
    lengthMiles: 10.0,
    elevationGainFt: 2000,
    trailhead: { lat: 48.5832, lng: -120.7374, name: "Rainy Pass PCT trailhead" },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "Switchback up through old-growth larch and silver fir to a pass with the eastern North Cascades unrolling east — at peak in late September, a sea of golden alpine larch.",
    highlights: ["Golden alpine larch end of Sept", "Cutthroat Peak granite spire", "Methow valley view"],
    parking:
      "Rainy Pass PCT lot on Highway 20 (mile 158). Northwest Forest Pass required. Highway closed in winter (typ. mid-Nov to mid-Apr).",
  },

  // ========== Olympic ==========
  {
    id: "marymere-falls",
    name: "Marymere Falls",
    region: "olympic",
    state: "WA",
    parkUnit: "Olympic National Park",
    difficulty: "easy",
    type: "day",
    ecosystem: "rainforest",
    lengthMiles: 1.8,
    elevationGainFt: 400,
    trailhead: { lat: 48.0581, lng: -123.7929, name: "Storm King Ranger Station" },
    permitRequired: false,
    bestSeasons: ["spring", "summer", "fall"],
    description:
      "The easiest waterfall hike in Olympic — a flat walk through old-growth fir along Lake Crescent to a 90-ft cascade splashing into a fern-walled grotto.",
    highlights: ["Old-growth Douglas fir", "90-ft Marymere Falls", "Lake Crescent shore"],
    parking:
      "Storm King Ranger Station lot off Highway 101 at Lake Crescent. Park entrance fee $30/vehicle (7 days). Holds 50+ cars; rarely fills.",
  },

  // ========== Mt Baker / Cascades extras ==========
  {
    id: "lake-22",
    name: "Lake Twenty-Two",
    region: "north-cascades",
    state: "WA",
    parkUnit: "Mt Baker–Snoqualmie National Forest",
    difficulty: "moderate",
    type: "day",
    ecosystem: "rainforest",
    lengthMiles: 5.4,
    elevationGainFt: 1350,
    trailhead: { lat: 48.0764, lng: -121.7456, name: "Lake 22 trailhead" },
    permitRequired: false,
    bestSeasons: ["spring", "summer", "fall"],
    description:
      "A switchback climb through ancient cedar and Douglas fir to a glacial cirque lake at the foot of Mt Pilchuck's south face — talus, waterfalls, the works.",
    highlights: ["Old-growth cedars", "Cirque lake against Pilchuck cliffs", "Waterfall braid on the climb"],
    parking:
      "Trailhead lot off Mountain Loop Highway, 13 mi east of Granite Falls. Northwest Forest Pass required. Holds 30 cars; fills by 8 a.m. summer weekends.",
  },
  {
    id: "chain-lakes",
    name: "Chain Lakes Loop",
    region: "north-cascades",
    state: "WA",
    parkUnit: "Mt Baker–Snoqualmie National Forest",
    difficulty: "hard",
    type: "day",
    ecosystem: "alpine",
    lengthMiles: 7.0,
    elevationGainFt: 1900,
    trailhead: { lat: 48.8467, lng: -121.6918, name: "Artist Point" },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "Mt Baker on one side, Mt Shuksan on the other, and a string of four alpine lakes between them — heathered ridges, blueberry slopes, and one of the densest mountain views in the Cascades.",
    highlights: ["Mt Baker + Mt Shuksan in one frame", "Four alpine lakes", "Heather meadows turn red in late September"],
    parking:
      "Artist Point lot at the end of Highway 542 (Mt Baker Highway). Free. Snowbound until mid-July most years; lot opens late July–Sept.",
  },

  // ========== SoCal coastal & San Gabriels ==========
  {
    id: "eaton-canyon",
    name: "Eaton Canyon Falls",
    region: "socal-desert",
    state: "CA",
    parkUnit: "Eaton Canyon Natural Area / Angeles NF",
    difficulty: "easy",
    type: "day",
    ecosystem: "chaparral",
    lengthMiles: 3.5,
    elevationGainFt: 400,
    trailhead: { lat: 34.1789, lng: -118.0972, name: "Eaton Canyon Nature Center" },
    permitRequired: false,
    bestSeasons: ["winter", "spring"],
    description:
      "An LA-classic family hike up a sandy wash to a 40-ft waterfall in a shaded slot. Easy, scrambly, and cool even in summer once the canyon narrows.",
    highlights: ["Chaparral wildflower spring", "40-ft First Falls", "Stream crossings"],
    parking:
      "Eaton Canyon Nature Center lot off Altadena Drive. Free. Holds 80 cars; fills by 9 a.m. on weekends — overflow parks along New York Drive.",
  },
  {
    id: "solstice-canyon",
    name: "Solstice Canyon",
    region: "socal-desert",
    state: "CA",
    parkUnit: "Santa Monica Mountains National Recreation Area",
    difficulty: "easy",
    type: "day",
    ecosystem: "chaparral",
    lengthMiles: 3.0,
    elevationGainFt: 500,
    trailhead: { lat: 34.0386, lng: -118.7383, name: "Solstice Canyon trailhead" },
    permitRequired: false,
    bestSeasons: ["winter", "spring", "fall"],
    description:
      "A shaded sycamore canyon north of Malibu ending at the burned-out Roberts Ranch — stone foundations, a tropical garden gone feral, and a small year-round waterfall.",
    highlights: ["Burned ranch ruins", "Sycamore-shaded creek", "Year-round trickling falls"],
    parking:
      "NPS lot at the trailhead off Corral Canyon Road. Free. Holds 60 cars; fills weekends 10–2.",
  },

  // ========== Mt St Helens ==========
  {
    id: "mt-st-helens",
    name: "Mt St Helens via Monitor Ridge",
    region: "rainier",
    state: "WA",
    parkUnit: "Mount St Helens National Volcanic Monument",
    difficulty: "extreme",
    type: "day",
    ecosystem: "volcanic",
    lengthMiles: 10.0,
    elevationGainFt: 4500,
    trailhead: { lat: 46.1551, lng: -122.1818, name: "Climbers' Bivouac" },
    permitRequired: true,
    bestSeasons: ["summer", "fall"],
    description:
      "A non-technical scramble up volcanic ash and house-sized boulders to the southern crater rim, where you stand 1,300 ft above the lava dome inside the 1980 blast amphitheater.",
    highlights: ["Stand on the crater rim", "View into the steaming dome", "Mt Adams + Mt Hood + Mt Rainier from the summit"],
    parking:
      "Climbers' Bivouac at the end of FS Road 830 (last 3 mi gravel). Climbing permit required Apr–Oct (mtsthelenspermit.com); 100/day, lottery in spring. NW Forest Pass for parking.",
  },

  // ========== Bay Area + Big Sur extras ==========
  {
    id: "mission-peak",
    name: "Mission Peak",
    region: "bigsur-bay",
    state: "CA",
    parkUnit: "Mission Peak Regional Preserve",
    difficulty: "moderate",
    type: "day",
    ecosystem: "chaparral",
    lengthMiles: 6.0,
    elevationGainFt: 2150,
    trailhead: { lat: 37.5119, lng: -121.9105, name: "Stanford Ave staging area" },
    permitRequired: false,
    bestSeasons: ["winter", "spring", "fall"],
    description:
      "South Bay's training mountain — a steep, exposed grunt up the western flank to the iconic 2,517-ft summit pole, with a 360° view from Mt Tam to Mt Hamilton on a clear day.",
    highlights: ["Iconic summit selfie pole", "South Bay 360° panorama", "Sunrise hike favorite"],
    parking:
      "Stanford Avenue staging area in Fremont. Free but residential — strictly enforced 2-hour limits on side streets. Lot fills by 7 a.m. weekends; the Ohlone College trailhead is the calmer alternative.",
  },
  {
    id: "point-lobos",
    name: "Point Lobos Perimeter",
    region: "bigsur-bay",
    state: "CA",
    parkUnit: "Point Lobos State Natural Reserve",
    difficulty: "easy",
    type: "day",
    ecosystem: "coastal",
    lengthMiles: 6.0,
    elevationGainFt: 600,
    trailhead: { lat: 36.5217, lng: -121.9367, name: "Point Lobos main entrance" },
    permitRequired: false,
    bestSeasons: ["spring", "summer", "fall", "winter"],
    description:
      "Stitch together North Shore, Cypress Grove, and South Shore trails for a perimeter of California's most photographed headland — sea otters, harbor seals, and the only naturally-occurring Monterey cypress grove on earth.",
    highlights: ["Cypress Grove twisted cypresses", "Sea Lion Point", "Bird Island gray-whale watching"],
    parking:
      "Main entrance lot off Highway 1, $10/vehicle day-use. Capacity is rationed — once full, cars are metered one-out / one-in. Avoid arrival 11–2 weekends.",
  },
  {
    id: "pfeiffer-falls",
    name: "Pfeiffer Falls & Valley View",
    region: "bigsur-bay",
    state: "CA",
    parkUnit: "Pfeiffer Big Sur State Park",
    difficulty: "easy",
    type: "day",
    ecosystem: "redwood",
    lengthMiles: 2.0,
    elevationGainFt: 400,
    trailhead: { lat: 36.2488, lng: -121.7878, name: "Pfeiffer Big Sur day-use" },
    permitRequired: false,
    bestSeasons: ["spring", "fall", "winter"],
    description:
      "A short loop into a redwood-shaded canyon, past a 60-ft waterfall, then up to the Valley View overlook framing the Big Sur River valley meeting the Pacific.",
    highlights: ["60-ft Pfeiffer Falls", "Old-growth redwood grove", "Valley-to-ocean overlook"],
    parking:
      "Pfeiffer Big Sur State Park day-use lot off Highway 1, $10/vehicle. Reopened 2021 after fire/flood reroute. Holds 70 cars; fills 10 a.m.–3 p.m. summer weekends.",
  },

  // ========== Crater Lake + central Oregon ==========
  {
    id: "mt-scott-crater",
    name: "Mount Scott (Crater Lake)",
    region: "oregon",
    state: "OR",
    parkUnit: "Crater Lake National Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "volcanic",
    lengthMiles: 4.4,
    elevationGainFt: 1250,
    trailhead: { lat: 42.9285, lng: -122.0181, name: "Mt Scott trailhead" },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "The highest point in Crater Lake NP at 8,929 ft — switchbacks across an open volcanic ridge to a fire lookout that floats above the entire caldera and the lake's deepest blue.",
    highlights: ["Highest point in the park", "Top-down view of Crater Lake", "Working CCC fire lookout"],
    parking:
      "Roadside pullout on East Rim Drive, mile 17 from Park HQ. Park entrance fee $30/vehicle. Rim Drive opens late June–Oct depending on snow.",
  },

  // ========== Columbia Gorge ==========
  {
    id: "angels-rest",
    name: "Angel's Rest",
    region: "oregon",
    state: "OR",
    parkUnit: "Columbia River Gorge National Scenic Area",
    difficulty: "moderate",
    type: "day",
    ecosystem: "gorge",
    lengthMiles: 4.5,
    elevationGainFt: 1500,
    trailhead: { lat: 45.561, lng: -122.1664, name: "Angel's Rest trailhead" },
    permitRequired: false,
    bestSeasons: ["spring", "summer", "fall"],
    description:
      "A steep workout up the gorge wall to a basalt prow jutting over the Columbia River — the closest wow-view from Portland and a regenerating after-burn forest from the 2017 Eagle Creek fire.",
    highlights: ["Coopey Falls early on the trail", "Basalt prow viewpoint", "Recovering post-fire forest"],
    parking:
      "Trailhead pullouts along Historic Columbia River Highway near mile 28. Free. Small lots — fills by 8 a.m. weekends; arrive early or use Bridal Veil overflow.",
  },
];

export const TRAILS: Trail[] = RAW_TRAILS.map((t) => ({
  ...t,
  popularity: POPULARITY_BY_ID[t.id] ?? "steady",
  scenery: SCENERY_BY_ID[t.id] ?? 3,
  // Inline `endpoint` on the entry (if any) wins; otherwise use the side-map
  endpoint: t.endpoint ?? ENDPOINT_BY_ID[t.id],
}));

export const TRAIL_BY_ID = Object.fromEntries(TRAILS.map((t) => [t.id, t])) as Record<string, Trail>;
