import type { Trail, Popularity } from "./types";

// Popularity tier per trail id. Read as a positive descriptor of the
// experience; "Backcountry" is not a danger label, it's a feature for
// people who want solitude (with the corresponding self-reliance).
//
// Calibration: based on AllTrails review counts, social-media presence,
// and traffic-per-mile estimates. Famous-but-linear thru-hikes (PCT,
// JMT) sit in `backcountry` because per-day-of-effort you'll see far
// fewer people than on a 4 mi viewpoint hike.
const POPULARITY_BY_ID: Record<string, Popularity> = {
  // Iconic — instantly recognized; you'll have company at viewpoints
  "half-dome": "iconic",
  "mist-trail": "iconic",
  "multnomah-wahkeena": "iconic",
  "hurricane-hill": "iconic",
  "hall-of-mosses": "iconic",
  "smith-rock": "iconic",
  "fern-canyon": "iconic",
  "bumpass-hell": "iconic",
  "mt-si": "iconic",
  "garfield-peak": "iconic",
  "maple-pass": "iconic",
  ewoldsen: "iconic",
  "sol-duc-falls": "iconic",
  "eagle-creek": "iconic",
  "skyline-paradise": "iconic",

  // Popular — every active hiker knows these; reliable foot traffic
  "clouds-rest": "popular",
  "upper-yosemite-falls": "popular",
  "cathedral-lakes": "popular",
  "sentinel-taft": "popular",
  "mt-whitney": "popular",
  "cascade-pass": "popular",
  "blue-lake": "popular",
  "naches-peak": "popular",
  burroughs: "popular",
  "storm-king": "popular",
  "mt-tam": "popular",
  "mt-diablo": "popular",
  "mt-baldy": "popular",
  "san-jacinto": "popular",
  "ryan-mountain": "popular",
  alamere: "popular",
  "tomales-point": "popular",
  "south-sister": "popular",
  "lassen-peak": "popular",
  "high-peaks-pinnacles": "popular",
  "andrew-molera": "popular",
  smugglers: "popular",

  // Steady — established and well-documented but with more breathing room
  "hidden-lake": "steady",
  heliotrope: "steady",
  "shi-shi": "steady",
  "high-divide": "steady",
  "tolmie-peak": "steady",
  wonderland: "steady",
  timberline: "steady",
  jmt: "steady",

  // Backcountry — multi-day or genuinely remote; expect long stretches alone
  "rae-lakes": "backcountry",
  "tahoe-rim": "backcountry",
  "lost-coast": "backcountry",
  "telescope-peak": "backcountry",
  pct: "backcountry",
};

const RAW_TRAILS: Omit<Trail, "popularity">[] = [
  // ========== Yosemite + High Sierra ==========
  {
    id: "half-dome",
    name: "Half Dome via Mist Trail",
    region: "yosemite-sierra",
    state: "CA",
    parkUnit: "Yosemite National Park",
    difficulty: "extreme",
    type: "day",
    ecosystem: "alpine",
    lengthMiles: 14.2,
    elevationGainFt: 4800,
    trailhead: { lat: 37.733, lng: -119.5575 },
    permitRequired: true,
    bestSeasons: ["summer", "fall"],
    description:
      "The most iconic day hike in the Sierra: thunderous waterfalls, granite staircases, and the legendary cable route up the back of Half Dome's 8,800-ft face. A 14-hour day for most. Cables typically up late May through mid-October.",
    highlights: ["Vernal & Nevada Falls", "Sub Dome cables", "Yosemite Valley summit views"],
    externalUrl: "https://www.nps.gov/yose/planyourvisit/halfdome.htm",
  },
  {
    id: "clouds-rest",
    name: "Cloud's Rest",
    region: "yosemite-sierra",
    state: "CA",
    parkUnit: "Yosemite National Park",
    difficulty: "hard",
    type: "day",
    ecosystem: "alpine",
    lengthMiles: 12,
    elevationGainFt: 2300,
    trailhead: { lat: 37.8307, lng: -119.4663 },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "A skinny granite spine rising 4,500 ft above Yosemite Valley, with what many consider the best view in the park — including a profile of Half Dome from above.",
    highlights: ["Granite ridge walk", "360° Sierra panorama", "View down on Half Dome"],
  },
  {
    id: "mist-trail",
    name: "Mist Trail (Vernal & Nevada Falls)",
    region: "yosemite-sierra",
    state: "CA",
    parkUnit: "Yosemite National Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "alpine",
    lengthMiles: 5.4,
    elevationGainFt: 1900,
    trailhead: { lat: 37.733, lng: -119.5575 },
    permitRequired: false,
    bestSeasons: ["spring", "summer"],
    description:
      "Yosemite Valley's signature waterfall trail. Climbs granite stairs straight through the spray of 317-ft Vernal Fall before continuing to the brink of 594-ft Nevada Fall.",
    highlights: ["Walk through waterfall mist", "Emerald Pool", "Liberty Cap"],
  },
  {
    id: "upper-yosemite-falls",
    name: "Upper Yosemite Falls",
    region: "yosemite-sierra",
    state: "CA",
    parkUnit: "Yosemite National Park",
    difficulty: "hard",
    type: "day",
    ecosystem: "alpine",
    lengthMiles: 7.2,
    elevationGainFt: 2700,
    trailhead: { lat: 37.7501, lng: -119.5972 },
    permitRequired: false,
    bestSeasons: ["spring", "summer", "fall"],
    description:
      "Switchbacks ascend the cliff next to North America's tallest waterfall. The brink view is exhilarating — and the falls themselves slow to a trickle by August.",
    highlights: ["Columbia Rock viewpoint", "Top of 2,425-ft falls", "Yosemite Point side trip"],
  },
  {
    id: "cathedral-lakes",
    name: "Cathedral Lakes",
    region: "yosemite-sierra",
    state: "CA",
    parkUnit: "Yosemite National Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "subalpine",
    lengthMiles: 7,
    elevationGainFt: 1000,
    trailhead: { lat: 37.873, lng: -119.3829 },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "Tuolumne Meadows' most beloved hike — a gentle climb through lodgepole forest to a pair of glacier-carved lakes beneath the spires of Cathedral Peak.",
    highlights: ["Cathedral Peak reflection", "Wildflower meadows", "Tioga Pass scenery"],
  },
  {
    id: "sentinel-taft",
    name: "Sentinel Dome + Taft Point Loop",
    region: "yosemite-sierra",
    state: "CA",
    parkUnit: "Yosemite National Park",
    difficulty: "easy",
    type: "day",
    ecosystem: "subalpine",
    lengthMiles: 5,
    elevationGainFt: 800,
    trailhead: { lat: 37.7128, lng: -119.5867 },
    permitRequired: false,
    bestSeasons: ["spring", "summer", "fall"],
    description:
      "Two of Yosemite's best viewpoints in a single short loop. Sentinel Dome offers a 360° panorama; Taft Point puts you on a 3,000-ft cliff edge with no railings.",
    highlights: ["Cliff-edge fissures at Taft Point", "Sentinel Dome 360 view", "Sunset spot"],
  },
  {
    id: "mt-whitney",
    name: "Mt Whitney Trail",
    region: "yosemite-sierra",
    state: "CA",
    parkUnit: "Inyo National Forest",
    difficulty: "extreme",
    type: "day",
    ecosystem: "alpine",
    lengthMiles: 22,
    elevationGainFt: 6600,
    trailhead: { lat: 36.5874, lng: -118.2398 },
    permitRequired: true,
    bestSeasons: ["summer"],
    description:
      "The contiguous USA's highest summit at 14,505 ft. A relentless 22-mile out-and-back gaining over 6,000 ft, with 99 switchbacks and altitude that breaks most hikers. Lottery permit required.",
    highlights: ["Highest peak in lower 48", "Trail Crest pass", "99 Switchbacks"],
    externalUrl: "https://www.recreation.gov/permits/233260",
  },
  {
    id: "jmt",
    name: "John Muir Trail (JMT)",
    region: "yosemite-sierra",
    state: "CA",
    parkUnit: "Yosemite to Sequoia",
    difficulty: "extreme",
    type: "thru-hike",
    ecosystem: "alpine",
    lengthMiles: 211,
    elevationGainFt: 47000,
    trailhead: { lat: 37.733, lng: -119.5575 },
    permitRequired: true,
    bestSeasons: ["summer"],
    description:
      "211 miles of high Sierra grandeur from Yosemite Valley to Mt Whitney's summit. Crosses 8 mountain passes above 11,000 ft and traverses three national parks. The premier thru-hike in the American West.",
    highlights: ["Donohue Pass", "Evolution Valley", "Forester Pass (highest point on PCT)", "Whitney summit finish"],
  },
  {
    id: "rae-lakes",
    name: "Rae Lakes Loop",
    region: "yosemite-sierra",
    state: "CA",
    parkUnit: "Kings Canyon National Park",
    difficulty: "hard",
    type: "multi-day",
    ecosystem: "alpine",
    lengthMiles: 41,
    elevationGainFt: 6900,
    trailhead: { lat: 36.7944, lng: -118.5836 },
    permitRequired: true,
    bestSeasons: ["summer", "fall"],
    description:
      "A classic 4–5 day Sierra backpacking loop through painted granite basins, alpine meadows, and a chain of cobalt lakes beneath the Painted Lady. Glen Pass at 11,978 ft is the crux.",
    highlights: ["Rae Lakes basin", "Glen Pass crossing", "Mist Falls"],
  },
  {
    id: "tahoe-rim",
    name: "Tahoe Rim Trail",
    region: "yosemite-sierra",
    state: "CA",
    parkUnit: "Lake Tahoe Basin",
    difficulty: "hard",
    type: "thru-hike",
    ecosystem: "subalpine",
    lengthMiles: 165,
    elevationGainFt: 24400,
    trailhead: { lat: 39.305, lng: -119.8941 },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "A 165-mile loop circling Lake Tahoe through six wilderness areas and three national forests. Average 8,000 ft elevation with constant lake views. Typically completed in 10–14 days or section-hiked.",
    highlights: ["Desolation Wilderness", "Mt Rose summit", "Continuous Tahoe views"],
  },

  // ========== Mt Rainier ==========
  {
    id: "wonderland",
    name: "Wonderland Trail",
    region: "rainier",
    state: "WA",
    parkUnit: "Mt Rainier National Park",
    difficulty: "extreme",
    type: "thru-hike",
    ecosystem: "subalpine",
    lengthMiles: 93,
    elevationGainFt: 22000,
    trailhead: { lat: 46.7506, lng: -121.8094 },
    permitRequired: true,
    bestSeasons: ["summer"],
    description:
      "A 93-mile loop entirely circling Mt Rainier — the most consistently spectacular thru-hike in the Pacific Northwest. Crosses every ecosystem on the mountain. 10–14 days; permit lottery is competitive.",
    highlights: ["Spray Park wildflowers", "Indian Bar", "Summerland", "Continuous Rainier views"],
    externalUrl: "https://www.nps.gov/mora/planyourvisit/the-wonderland-trail.htm",
  },
  {
    id: "skyline-paradise",
    name: "Skyline Trail (Paradise)",
    region: "rainier",
    state: "WA",
    parkUnit: "Mt Rainier National Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "subalpine",
    lengthMiles: 5.5,
    elevationGainFt: 1700,
    trailhead: { lat: 46.7864, lng: -121.7355 },
    permitRequired: false,
    bestSeasons: ["summer"],
    description:
      "The crown-jewel day hike from Paradise. Climbs through wildflower meadows to Panorama Point, framed by glaciers and the Tatoosh Range. Peak bloom in late July.",
    highlights: ["Myrtle Falls", "Panorama Point", "Nisqually Glacier overlook"],
  },
  {
    id: "naches-peak",
    name: "Naches Peak Loop",
    region: "rainier",
    state: "WA",
    parkUnit: "Mt Rainier National Park",
    difficulty: "easy",
    type: "day",
    ecosystem: "subalpine",
    lengthMiles: 3.2,
    elevationGainFt: 600,
    trailhead: { lat: 46.8717, lng: -121.5197 },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "A short, family-friendly loop at Chinook Pass that delivers maximum scenery per step: alpine tarns, wildflowers, and a head-on Rainier portrait.",
    highlights: ["Tipsoo Lake reflection", "PCT segment", "Fall huckleberries"],
  },
  {
    id: "burroughs",
    name: "Burroughs Mountain",
    region: "rainier",
    state: "WA",
    parkUnit: "Mt Rainier National Park",
    difficulty: "hard",
    type: "day",
    ecosystem: "alpine",
    lengthMiles: 9,
    elevationGainFt: 2500,
    trailhead: { lat: 46.9145, lng: -121.6428 },
    permitRequired: false,
    bestSeasons: ["summer"],
    description:
      "An arctic-tundra plateau on Rainier's NE flank. Three Burroughs summits get progressively closer to the Emmons Glacier. The closest you can stand to the mountain without a rope.",
    highlights: ["Emmons Glacier overlook", "Tundra ecosystem", "Frozen Lake"],
  },
  {
    id: "tolmie-peak",
    name: "Tolmie Peak Lookout",
    region: "rainier",
    state: "WA",
    parkUnit: "Mt Rainier National Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "subalpine",
    lengthMiles: 6.5,
    elevationGainFt: 1100,
    trailhead: { lat: 46.9337, lng: -121.8631 },
    permitRequired: false,
    bestSeasons: ["summer"],
    description:
      "A historic fire lookout perched above Eunice Lake with a postcard view of Rainier. The drive to Mowich Lake is bumpy gravel — and worth every mile.",
    highlights: ["Eunice Lake", "Restored 1933 fire lookout", "Mowich Lake"],
  },

  // ========== Olympic NP ==========
  {
    id: "hall-of-mosses",
    name: "Hall of Mosses (Hoh Rainforest)",
    region: "olympic",
    state: "WA",
    parkUnit: "Olympic National Park",
    difficulty: "easy",
    type: "day",
    ecosystem: "rainforest",
    lengthMiles: 0.8,
    elevationGainFt: 100,
    trailhead: { lat: 47.8606, lng: -123.9352 },
    permitRequired: false,
    bestSeasons: ["spring", "summer", "fall", "winter"],
    description:
      "An otherworldly stroll through one of the few temperate rainforests on Earth. Big-leaf maples drip with club moss; everything glows green.",
    highlights: ["Old-growth Sitka spruce", "Moss-draped maples", "Year-round trail"],
  },
  {
    id: "hurricane-hill",
    name: "Hurricane Hill",
    region: "olympic",
    state: "WA",
    parkUnit: "Olympic National Park",
    difficulty: "easy",
    type: "day",
    ecosystem: "subalpine",
    lengthMiles: 3.2,
    elevationGainFt: 700,
    trailhead: { lat: 47.9778, lng: -123.5183 },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "A paved-then-dirt path to a 5,757-ft summit with views from the Olympic interior to Vancouver Island. Black-tailed deer and marmots are routine sightings.",
    highlights: ["Strait of Juan de Fuca view", "Mt Olympus skyline", "Wildflowers"],
  },
  {
    id: "storm-king",
    name: "Mt Storm King",
    region: "olympic",
    state: "WA",
    parkUnit: "Olympic National Park",
    difficulty: "hard",
    type: "day",
    ecosystem: "rainforest",
    lengthMiles: 4.1,
    elevationGainFt: 2100,
    trailhead: { lat: 48.0589, lng: -123.7886 },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "A brutally steep scramble above Lake Crescent that ends at fixed ropes climbing onto a knife-edge summit. The view straight down 2,000 ft to the lake is unforgettable.",
    highlights: ["Lake Crescent overlook", "Rope-assisted scramble", "Marymere Falls add-on"],
  },
  {
    id: "shi-shi",
    name: "Shi Shi Beach + Point of the Arches",
    region: "olympic",
    state: "WA",
    parkUnit: "Olympic National Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "coastal",
    lengthMiles: 8,
    elevationGainFt: 200,
    trailhead: { lat: 48.2792, lng: -124.6794 },
    permitRequired: true,
    bestSeasons: ["spring", "summer", "fall"],
    description:
      "Wild Pacific coast at its rawest: a muddy boardwalk forest gives way to two miles of sand and ends at the sea-stack labyrinth of Point of the Arches. Tide-aware planning required.",
    highlights: ["Sea stacks", "Tidepools", "Beach camping"],
  },
  {
    id: "high-divide",
    name: "High Divide / Seven Lakes Basin Loop",
    region: "olympic",
    state: "WA",
    parkUnit: "Olympic National Park",
    difficulty: "hard",
    type: "multi-day",
    ecosystem: "subalpine",
    lengthMiles: 19,
    elevationGainFt: 3500,
    trailhead: { lat: 47.9542, lng: -123.8344 },
    permitRequired: true,
    bestSeasons: ["summer"],
    description:
      "Olympic NP's premier backpacking loop: cobalt lake basins, a high ridge facing the Mt Olympus icefields, and constant black bear sightings in late summer.",
    highlights: ["Mt Olympus glacier views", "Heart Lake", "Bogachiel Peak"],
  },
  {
    id: "sol-duc-falls",
    name: "Sol Duc Falls",
    region: "olympic",
    state: "WA",
    parkUnit: "Olympic National Park",
    difficulty: "easy",
    type: "day",
    ecosystem: "rainforest",
    lengthMiles: 1.6,
    elevationGainFt: 200,
    trailhead: { lat: 47.9542, lng: -123.8344 },
    permitRequired: false,
    bestSeasons: ["spring", "summer", "fall", "winter"],
    description:
      "A flat, family-friendly walk through old-growth Douglas fir to a triple-channel waterfall plunging into a mossy gorge. Especially beautiful in winter when accessible.",
    highlights: ["Triple-cascade falls", "Old-growth forest", "Year-round trail"],
  },

  // ========== North Cascades ==========
  {
    id: "maple-pass",
    name: "Maple Pass Loop",
    region: "north-cascades",
    state: "WA",
    parkUnit: "Okanogan-Wenatchee National Forest",
    difficulty: "moderate",
    type: "day",
    ecosystem: "subalpine",
    lengthMiles: 7.2,
    elevationGainFt: 2000,
    trailhead: { lat: 48.5167, lng: -120.7383 },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "Widely considered the best day-hike loop in the North Cascades. A ridge walk with views into Lake Ann, Heather Pass, and a sea of jagged peaks. Larch gold in late September.",
    highlights: ["Larch trees in fall", "Lake Ann overlook", "Heather Pass ridgeline"],
  },
  {
    id: "cascade-pass",
    name: "Cascade Pass + Sahale Arm",
    region: "north-cascades",
    state: "WA",
    parkUnit: "North Cascades National Park",
    difficulty: "hard",
    type: "day",
    ecosystem: "alpine",
    lengthMiles: 12,
    elevationGainFt: 4000,
    trailhead: { lat: 48.4744, lng: -121.0759 },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "From a saddle deep in the North Cascades, climb a knife ridge to Sahale Glacier Camp at 7,600 ft — surrounded on all sides by the most rugged peaks in the lower 48.",
    highlights: ["Sahale Glacier", "Mountain goats", "Most dramatic skyline in the range"],
  },
  {
    id: "blue-lake",
    name: "Blue Lake (Washington Pass)",
    region: "north-cascades",
    state: "WA",
    parkUnit: "Okanogan-Wenatchee National Forest",
    difficulty: "easy",
    type: "day",
    ecosystem: "subalpine",
    lengthMiles: 4.4,
    elevationGainFt: 1100,
    trailhead: { lat: 48.5215, lng: -120.67 },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "A short approach to a turquoise alpine lake surrounded by Liberty Bell, Early Winter Spires, and (in autumn) golden larches. The lowest-effort big payoff in the Cascades.",
    highlights: ["Liberty Bell spires", "Larches in October", "Beginner-friendly alpine"],
  },
  {
    id: "hidden-lake",
    name: "Hidden Lake Lookout",
    region: "north-cascades",
    state: "WA",
    parkUnit: "Mt Baker-Snoqualmie National Forest",
    difficulty: "hard",
    type: "day",
    ecosystem: "alpine",
    lengthMiles: 8,
    elevationGainFt: 3300,
    trailhead: { lat: 48.5066, lng: -121.2076 },
    permitRequired: false,
    bestSeasons: ["summer"],
    description:
      "A rugged climb to a historic 1931 fire lookout perched at 6,890 ft on a granite spike — with one of the most photographed views in Washington.",
    highlights: ["1931 fire lookout", "Granite ridge scramble", "Hidden Lake view"],
  },
  {
    id: "heliotrope",
    name: "Heliotrope Ridge (Mt Baker)",
    region: "north-cascades",
    state: "WA",
    parkUnit: "Mt Baker-Snoqualmie National Forest",
    difficulty: "moderate",
    type: "day",
    ecosystem: "alpine",
    lengthMiles: 5.5,
    elevationGainFt: 1900,
    trailhead: { lat: 48.7864, lng: -121.8453 },
    permitRequired: false,
    bestSeasons: ["summer"],
    description:
      "A climber's approach trail that gets non-climbers within 100 yards of the Coleman Glacier. Crevasse views without ice axes.",
    highlights: ["Coleman Glacier toe", "Mt Baker close-up", "Stream crossings"],
  },

  // ========== Oregon Cascades + Gorge ==========
  {
    id: "timberline",
    name: "Timberline Trail (Mt Hood)",
    region: "oregon",
    state: "OR",
    parkUnit: "Mt Hood National Forest",
    difficulty: "hard",
    type: "multi-day",
    ecosystem: "subalpine",
    lengthMiles: 41,
    elevationGainFt: 9000,
    trailhead: { lat: 45.3309, lng: -121.7113 },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "A 41-mile loop circumnavigating Mt Hood — Oregon's signature multi-day backpack. Glacial river fords, wildflower meadows, and a continuous 11,250-ft mountain overhead.",
    highlights: ["Ramona Falls", "Eliot Glacier crossing", "Paradise Park wildflowers"],
  },
  {
    id: "garfield-peak",
    name: "Garfield Peak (Crater Lake)",
    region: "oregon",
    state: "OR",
    parkUnit: "Crater Lake National Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "volcanic",
    lengthMiles: 3.6,
    elevationGainFt: 1000,
    trailhead: { lat: 42.9119, lng: -122.1456 },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "The best Crater Lake viewpoint without a backcountry permit. Climbs from Rim Village to an 8,054-ft summit with the entire caldera at your feet.",
    highlights: ["Caldera-top panorama", "Wizard Island view", "Klamath Basin distant view"],
  },
  {
    id: "south-sister",
    name: "South Sister Summit",
    region: "oregon",
    state: "OR",
    parkUnit: "Three Sisters Wilderness",
    difficulty: "hard",
    type: "day",
    ecosystem: "volcanic",
    lengthMiles: 12,
    elevationGainFt: 4900,
    trailhead: { lat: 44.0317, lng: -121.7572 },
    permitRequired: true,
    bestSeasons: ["summer"],
    description:
      "A nontechnical climb to the 10,358-ft summit of Oregon's third-tallest peak. Volcanic gravel, a summit crater lake, and views of the entire Cascades chain.",
    highlights: ["Summit crater lake", "Middle and North Sister profile", "Lewis Glacier"],
  },
  {
    id: "eagle-creek",
    name: "Eagle Creek to Tunnel Falls",
    region: "oregon",
    state: "OR",
    parkUnit: "Columbia River Gorge",
    difficulty: "moderate",
    type: "day",
    ecosystem: "gorge",
    lengthMiles: 12,
    elevationGainFt: 1640,
    trailhead: { lat: 45.6361, lng: -121.9197 },
    permitRequired: false,
    bestSeasons: ["spring", "fall"],
    description:
      "A waterfall-after-waterfall trail along a basalt-walled creek, climaxing with a tunnel cut behind 175-ft Tunnel Falls. Cliff-edge trail with cable handholds — not for the height-averse.",
    highlights: ["Punchbowl Falls", "High Bridge", "Walk behind Tunnel Falls"],
  },
  {
    id: "multnomah-wahkeena",
    name: "Multnomah-Wahkeena Falls Loop",
    region: "oregon",
    state: "OR",
    parkUnit: "Columbia River Gorge",
    difficulty: "moderate",
    type: "day",
    ecosystem: "gorge",
    lengthMiles: 5,
    elevationGainFt: 1600,
    trailhead: { lat: 45.576, lng: -122.1158 },
    permitRequired: false,
    bestSeasons: ["spring", "fall", "winter"],
    description:
      "Connects Oregon's two most famous waterfalls in a forested loop. Multnomah Falls is 620 ft of two-tier drama; Wahkeena adds a ribbon cascade behind it.",
    highlights: ["Multnomah Falls", "Wahkeena Falls", "Benson Bridge"],
  },
  {
    id: "smith-rock",
    name: "Misery Ridge Loop (Smith Rock)",
    region: "oregon",
    state: "OR",
    parkUnit: "Smith Rock State Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "desert",
    lengthMiles: 3.7,
    elevationGainFt: 1100,
    trailhead: { lat: 44.3679, lng: -121.1395 },
    permitRequired: false,
    bestSeasons: ["spring", "fall"],
    description:
      "A short, intensely scenic loop above the Crooked River canyon. Rock climbers hang from every overhang — Smith Rock is the birthplace of American sport climbing.",
    highlights: ["Monkey Face spire", "Crooked River canyon", "Rock climbers everywhere"],
  },

  // ========== Northern California ==========
  {
    id: "lassen-peak",
    name: "Lassen Peak",
    region: "norcal",
    state: "CA",
    parkUnit: "Lassen Volcanic National Park",
    difficulty: "hard",
    type: "day",
    ecosystem: "volcanic",
    lengthMiles: 5,
    elevationGainFt: 2000,
    trailhead: { lat: 40.4732, lng: -121.5036 },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "Climb to the 10,457-ft summit of one of America's most recently active volcanoes (1915). Views of Mt Shasta, the Sierra, and the steaming hydrothermal areas below.",
    highlights: ["Active volcano summit", "Mt Shasta view", "Steam vents"],
  },
  {
    id: "bumpass-hell",
    name: "Bumpass Hell (Lassen)",
    region: "norcal",
    state: "CA",
    parkUnit: "Lassen Volcanic National Park",
    difficulty: "easy",
    type: "day",
    ecosystem: "volcanic",
    lengthMiles: 3,
    elevationGainFt: 500,
    trailhead: { lat: 40.4565, lng: -121.5028 },
    permitRequired: false,
    bestSeasons: ["summer", "fall"],
    description:
      "A boardwalk through the largest hydrothermal area in the park. Boiling mud pots, fumaroles, and turquoise pools — Yellowstone, but with no crowds.",
    highlights: ["Boiling mud pots", "Fumaroles", "Boardwalk through hot springs"],
  },
  {
    id: "fern-canyon",
    name: "Fern Canyon Loop (Prairie Creek)",
    region: "norcal",
    state: "CA",
    parkUnit: "Prairie Creek Redwoods State Park",
    difficulty: "easy",
    type: "day",
    ecosystem: "redwood",
    lengthMiles: 1,
    elevationGainFt: 100,
    trailhead: { lat: 41.4002, lng: -124.0653 },
    permitRequired: true,
    bestSeasons: ["summer", "fall"],
    description:
      "A 50-foot-deep canyon walled in seven species of fern. Filmed for Jurassic Park 2. Timed-entry permit required May–September; expect to wade.",
    highlights: ["Fern-covered canyon walls", "Jurassic Park filming location", "Coastal redwoods nearby"],
  },
  {
    id: "lost-coast",
    name: "Lost Coast Trail",
    region: "norcal",
    state: "CA",
    parkUnit: "King Range National Conservation Area",
    difficulty: "hard",
    type: "multi-day",
    ecosystem: "coastal",
    lengthMiles: 25,
    elevationGainFt: 1500,
    trailhead: { lat: 40.2911, lng: -124.3528 },
    permitRequired: true,
    bestSeasons: ["spring", "fall"],
    description:
      "California's only true wilderness coastline — 25 miles of black-sand beaches between two roads. Tide-dependent: two impassable zones must be crossed at low water. Bear cans required.",
    highlights: ["Black sand beaches", "Tide-required passages", "Roosevelt elk and seals"],
  },

  // ========== Southern CA + Desert ==========
  {
    id: "ryan-mountain",
    name: "Ryan Mountain (Joshua Tree)",
    region: "socal-desert",
    state: "CA",
    parkUnit: "Joshua Tree National Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "desert",
    lengthMiles: 3,
    elevationGainFt: 1000,
    trailhead: { lat: 33.9852, lng: -116.133 },
    permitRequired: false,
    bestSeasons: ["fall", "winter", "spring"],
    description:
      "A short, steep ascent to the centerpiece summit of Joshua Tree NP. The 360° view spans the Wonderland of Rocks, the Salton Sea, and (on clear days) the snowcapped San Gorgonio range.",
    highlights: ["Wonderland of Rocks view", "Sunrise/sunset hike", "San Gorgonio in winter"],
  },
  {
    id: "telescope-peak",
    name: "Telescope Peak (Death Valley)",
    region: "socal-desert",
    state: "CA",
    parkUnit: "Death Valley National Park",
    difficulty: "hard",
    type: "day",
    ecosystem: "desert",
    lengthMiles: 14,
    elevationGainFt: 3000,
    trailhead: { lat: 36.2306, lng: -117.0644 },
    permitRequired: false,
    bestSeasons: ["spring", "fall"],
    description:
      "The highest point in Death Valley NP at 11,049 ft, named for its commanding view of both Badwater (-282 ft) and Mt Whitney (14,505 ft) on the same horizon.",
    highlights: ["Bristlecone pines", "Badwater + Whitney visible together", "Snow possible into June"],
  },
  {
    id: "san-jacinto",
    name: "Mt San Jacinto via Tram",
    region: "socal-desert",
    state: "CA",
    parkUnit: "San Jacinto State Wilderness",
    difficulty: "moderate",
    type: "day",
    ecosystem: "alpine",
    lengthMiles: 11,
    elevationGainFt: 2300,
    trailhead: { lat: 33.8125, lng: -116.6402 },
    permitRequired: false,
    bestSeasons: ["spring", "summer", "fall"],
    description:
      "Ride the Palm Springs Aerial Tramway from desert floor to 8,500 ft, then hike 5.5 miles to a 10,834-ft summit overlooking Coachella Valley. The biggest single-day vertical relief in the lower 48.",
    highlights: ["Aerial tram approach", "Round Valley meadow", "Summit boulder scramble"],
  },
  {
    id: "mt-baldy",
    name: "Mt Baldy (Devil's Backbone)",
    region: "socal-desert",
    state: "CA",
    parkUnit: "Angeles National Forest",
    difficulty: "hard",
    type: "day",
    ecosystem: "chaparral",
    lengthMiles: 11,
    elevationGainFt: 3900,
    trailhead: { lat: 34.2606, lng: -117.6314 },
    permitRequired: false,
    bestSeasons: ["spring", "summer", "fall"],
    description:
      "LA's home mountain at 10,064 ft. The Devil's Backbone ridge is the classic loop — narrow, exposed, and topping out with views from Catalina to the Mojave.",
    highlights: ["Devil's Backbone ridge", "Catalina Island view", "Bighorn sheep"],
  },
  {
    id: "smugglers",
    name: "Smugglers Cove (Channel Islands)",
    region: "socal-desert",
    state: "CA",
    parkUnit: "Channel Islands National Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "coastal",
    lengthMiles: 7.5,
    elevationGainFt: 1000,
    trailhead: { lat: 34.0489, lng: -119.5572 },
    permitRequired: false,
    bestSeasons: ["spring", "fall", "winter"],
    description:
      "A boat ride from Ventura, then a coastal traverse on Santa Cruz Island to a quiet cove. Endemic island foxes, sea cliffs, and zero crowds make this America's least-visited NP shine.",
    highlights: ["Island fox sightings", "Sea-cliff vistas", "Olive grove ruins at Smugglers"],
  },

  // ========== Big Sur + Bay Area ==========
  {
    id: "ewoldsen",
    name: "Ewoldsen Trail (McWay Falls)",
    region: "bigsur-bay",
    state: "CA",
    parkUnit: "Julia Pfeiffer Burns State Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "redwood",
    lengthMiles: 4.5,
    elevationGainFt: 1500,
    trailhead: { lat: 36.1574, lng: -121.6707 },
    permitRequired: false,
    bestSeasons: ["spring", "summer", "fall", "winter"],
    description:
      "A redwood-canyon loop above the Big Sur coast, paired with the iconic McWay Falls overlook — an 80-ft waterfall plunging directly onto the beach.",
    highlights: ["McWay Falls overlook", "Redwood canyon", "Pacific Ocean panorama"],
  },
  {
    id: "tomales-point",
    name: "Tomales Point",
    region: "bigsur-bay",
    state: "CA",
    parkUnit: "Point Reyes National Seashore",
    difficulty: "moderate",
    type: "day",
    ecosystem: "coastal",
    lengthMiles: 9.5,
    elevationGainFt: 1100,
    trailhead: { lat: 38.1873, lng: -122.9495 },
    permitRequired: false,
    bestSeasons: ["spring", "fall", "winter"],
    description:
      "A windswept ridge to the northern tip of Point Reyes, walking through the Tule Elk Reserve. Hundreds of elk, two bays, and one lighthouse on the horizon.",
    highlights: ["Tule elk herd", "Ocean and bay simultaneously", "Wildflowers in spring"],
  },
  {
    id: "alamere",
    name: "Alamere Falls (Coast Trail)",
    region: "bigsur-bay",
    state: "CA",
    parkUnit: "Point Reyes National Seashore",
    difficulty: "moderate",
    type: "day",
    ecosystem: "coastal",
    lengthMiles: 13,
    elevationGainFt: 1300,
    trailhead: { lat: 37.9368, lng: -122.747 },
    permitRequired: false,
    bestSeasons: ["winter", "spring"],
    description:
      "A rare 'tidefall' that drops directly onto the beach. The 13-mile coastal trail passes hidden lakes and cliff-edge prairie before the final scramble down to the falls.",
    highlights: ["Tidefall onto beach", "Bass Lake swim", "Bobcat sightings"],
  },
  {
    id: "mt-tam",
    name: "Mt Tamalpais East Peak Loop",
    region: "bigsur-bay",
    state: "CA",
    parkUnit: "Mt Tamalpais State Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "chaparral",
    lengthMiles: 6,
    elevationGainFt: 1700,
    trailhead: { lat: 37.9286, lng: -122.5797 },
    permitRequired: false,
    bestSeasons: ["spring", "fall", "winter"],
    description:
      "The Bay Area's signature mountain. The East Peak summit looks over San Francisco, the Farallon Islands, and the Sierra crest on rare crystal days.",
    highlights: ["SF skyline view", "Old Railroad Grade", "Verna Dunshee summit loop"],
  },
  {
    id: "andrew-molera",
    name: "Andrew Molera Headlands Loop",
    region: "bigsur-bay",
    state: "CA",
    parkUnit: "Andrew Molera State Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "coastal",
    lengthMiles: 8,
    elevationGainFt: 1100,
    trailhead: { lat: 36.2867, lng: -121.8461 },
    permitRequired: false,
    bestSeasons: ["spring", "fall", "winter"],
    description:
      "Big Sur's best loop hike: bluff-top trails over crashing surf, a hidden beach, and a riverfront return through cottonwoods.",
    highlights: ["Bluff-top ocean views", "Molera Beach", "Big Sur River mouth"],
  },
  {
    id: "mt-diablo",
    name: "Mt Diablo Summit Loop",
    region: "bigsur-bay",
    state: "CA",
    parkUnit: "Mt Diablo State Park",
    difficulty: "hard",
    type: "day",
    ecosystem: "chaparral",
    lengthMiles: 6.4,
    elevationGainFt: 2100,
    trailhead: { lat: 37.921, lng: -121.9377 },
    permitRequired: false,
    bestSeasons: ["spring", "fall", "winter"],
    description:
      "A steep climb to a 3,849-ft summit with one of the largest viewable areas of any peak in North America: from the Sierra to the Farallon Islands on a clear day.",
    highlights: ["35-state-equivalent visible area", "Wildflower super-blooms", "Mary Bowerman summit loop"],
  },
  {
    id: "high-peaks-pinnacles",
    name: "High Peaks Trail (Pinnacles)",
    region: "bigsur-bay",
    state: "CA",
    parkUnit: "Pinnacles National Park",
    difficulty: "moderate",
    type: "day",
    ecosystem: "chaparral",
    lengthMiles: 6.7,
    elevationGainFt: 1500,
    trailhead: { lat: 36.4906, lng: -121.1825 },
    permitRequired: false,
    bestSeasons: ["winter", "spring", "fall"],
    description:
      "Steel handholds carved into volcanic spires take you through one of the West's most reliable California condor habitats. America's youngest national park.",
    highlights: ["California condor sightings", "Stairs cut into rock", "Talus caves nearby"],
  },

  // ========== Iconic Thru-Hikes / Misc ==========
  {
    id: "pct",
    name: "Pacific Crest Trail (PCT)",
    region: "thru-hike",
    state: "Multi",
    parkUnit: "Mexico to Canada",
    difficulty: "extreme",
    type: "thru-hike",
    ecosystem: "alpine",
    lengthMiles: 2650,
    elevationGainFt: 489000,
    trailhead: { lat: 32.5959, lng: -116.467 },
    permitRequired: true,
    bestSeasons: ["spring", "summer", "fall"],
    description:
      "2,650 miles from Mexico to Canada through every major mountain range on the West Coast. A 5–6 month commitment that has become a generational rite of passage. Long-distance permit issued by lottery.",
    highlights: ["3 states, 25 national forests, 7 national parks", "From desert to glaciers", "The most photographed thru-hike in the world"],
    externalUrl: "https://www.pcta.org/discover-the-trail/permits/long-distance-permit/",
  },
  {
    id: "mt-si",
    name: "Mt Si",
    region: "north-cascades",
    state: "WA",
    parkUnit: "Mt Si Natural Resources Conservation Area",
    difficulty: "hard",
    type: "day",
    ecosystem: "rainforest",
    lengthMiles: 8,
    elevationGainFt: 3150,
    trailhead: { lat: 47.4885, lng: -121.7228 },
    permitRequired: false,
    bestSeasons: ["spring", "summer", "fall"],
    description:
      "Seattle's training-mountain-of-record. A relentless forested climb 30 minutes from downtown, ending at a haystack summit overlooking the Snoqualmie Valley.",
    highlights: ["Seattle skyline view", "Cascades to Olympic panorama", "Year-round access"],
  },
];

export const TRAILS: Trail[] = RAW_TRAILS.map((t) => ({
  ...t,
  popularity: POPULARITY_BY_ID[t.id] ?? "steady",
}));

export const TRAIL_BY_ID = Object.fromEntries(TRAILS.map((t) => [t.id, t])) as Record<string, Trail>;
